### ISSUE TITLE
допиливание "precise search"

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#100]
A) Закрыть задачи 98 и 99
Б) По смыслу эти задачи частично переходят в текущую задачу, но в другой блок (в "precise search").

Переделка относится лишь к длинным данным. Как она будет работать с короткими данными не очень ясно и лучше ничего не трогать.
На данный момент поиск пульсара в "precise search" идет следующим образом
а) выбираем модуль, луч, период, меру дисперсии (или "-1" для всех мер дисперсий) и центральное время относительно которого выбираются несколько кусков времени на каждом из которых перебираются периоды и меры дисперсии и ищется такой период и такая мера дисперсии на которых отношение сигнала к шуму максимально + если сигнал к шуму оказывается меньше 4 сигма, то в конечном файле ничего не запоминается.

Нужна переделка, которая делает определение пульсара в записях с двойным периодом. Она должна делать следующее:
1) При переборе периодов на данной мере дисперсии ищутся максимумы сигналов к шуму  которые больше 2.5сигма такие, чтобы на расстоянии периода (+ проверка по одной соседней от этого максимума точек) от них стоял еще один максимум у которого его величина отличается от величины найденного первого максимума не больше, чем на 20%. 
2) Если второй максимум не находится, то в конечный файл делается запись на периоде, который был указан в качестве начального проверочного и указывать ту меру дисперсии на которой и проводился поиск. Отношение сигнала к шуму брать то, какое получилось для максимальной точки в этой записи (в любом случае оно не будет меньше 1 и больше 2.5). 

Таким образом в конечном файле, который будет читаться программой "pulsar analytics" ВСЕГДА будут 200 мер дисперсии, но сигналы к шуму будут не от уровня 4 сигма, а от уровня (как я ожидаю) 2 сигма.

**Comment by vtyulb** [comment]
Сделано
