### ISSUE TITLE
откат задач 98 и 99

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#102]
Все таки нужно переделывать не "precise search", а "pulsar analytics".  Часть работы, наверно, можно просто скопировать из задач 98 и 99.
При загрузке файлов, полученных в  "precise search" для "pulsar analytics" проделывать следующие процедуры:
1) читаем данные, проверяем найденный пик в сигма шумов
2) смотрим относительно этого пика на расстоянии периода плюс минус одна точка второй пик.
3) проверяем максимальное значение точек в массиве со средним двойным профилем в области второго пика. Если:
    а) величина второго пика отличается больше, чем 30% от высоты первого пика, то присваиваем этой мере дисперсии SNR=2.
     б) величина второго пика отличается меньше, чем на 30% от высоты первого пика, то запоминаем сигнал шум первого максимума
4) Если в ходе работы на каких-то мерах дисперсии источник не обнаружен, то присваиваем этой мере дисперсии SNR=1
5) Таким образом, как для "длинных", так и для "коротких" данных в памяти будет сидеть массив из мер дисперсий от 1 до 200.
6) Процедура "plot" в новом режиме, как и "mem", "m+" должна срабатывать, если нажата галочка "different maximus", если галочка "different maximus" не нажата, то программа работает в том же режиме, что и раньше.
7) "**Внимание**", сам файл полученный в "precise search" никак не меняется, меняется лишь картинка на экране при дополнительном фильтре "different maximus"!!!

**Comment by vtyulb** [comment]
Сделано
