### ISSUE TITLE
Разобраться, почему не все пики ищутся или не правильно ищутся

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#105]
1) Часть пиков, причем довольно высоких, могут программой игнорироваться. Т.е., синяя стрелка их просто пропускает.
2) Часть пиков программа видит, но стрелку ставит не в том месте, т.е. не на вершине. Из-за этого определяется неправильный период в таблице.
3) При определении в ручном режиме периода, когда мышкой подводишь стрелку к максимуму гармоники период не совпадает с периодом табличным, когда программа находит максимум в автоматическом режиме

**Comment by vtyulb** [comment]
fixed
