### ISSUE TITLE
плотность потока в единицах температуры

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#106]
1) Плотность потока обычных источников (не пульсаров) загадочным образом появляется когда работаешь в окошке "edit". При этом автоматически ищется ступенька и делаются все необходимые вещи.
Для удобства работы нужно ввести дополнительный блок в меню. Сразу после "Investigation of pulsar" сделать блок "Non pulsar flux". При этом внутри меню должна стоять одна галочка с надписью "estimation of flux". Если эта галочка нажата, то появляется твоя вертикальная линия и с ее помощью определяется плотность потока по всем каналам + отдельный сводный поток. Если она не нажата, то никакой вертикальной линии быть не должно. Она сильно мешает.
2) Плотность потока у нас также определяется для пульсаров. 
Так как ступеньки уже могут искаться в автоматическом режиме, то "путь к ступеньке" можно убрать. Что за параметр "номер точек" я не знаю и похоже, что он говорит о том с какой и по какую точку в исходном файле брать интервал для оценки плотности потока. Правильнее плотность потока оценивать в интервале плюс минус одна или полторы минуты от вершины пульсара. Т.е. с целью однообразия нужно вместо "номер точек" ввести параметр "time", как и в "precise search", который просто является координатой пульсара на 2000 год, она должна пересчитываться на год наблюдений и от нее и берется интервал плюс минус 1 минута от вершины. В этом интервале производится усреднение импульсов и оценивается плотность потока, которая выводится на экран также как и для пункта 1).
3) "rotation measure" занимается тем же, что и пункт 2), но в отдельных частотных каналах. Предлагаю этот пункт вообще выкинуть, а там где мы определяем плотность потока ввести дополнительную галочку "rotation measure". Если она нажата, то помимо интегральной плотности потока на выход должны подаваться значения плотности потока в отдельных каналах. Типа того, как это сделано для пункта 1)

**Comment by vtyulb** [comment]
Сделано
