### ISSUE TITLE
Убрать из меню "precise timing"

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#107]
Пункт "precise timing" у нас не заработал и тем простым способом, как я предлагал он и не заработает. Может быть в будущем я придумаю, что с ним сделать, а пока предлагаю окошко с ним сделать не активным, то есть оно должно всегда быть серым цветом и так, чтобы в него нельзя было войти. Совсем его убирать не надо, быть может удастся в будущем его поправить.

**Comment by vtyulb** [comment]
Сделано
