### ISSUE TITLE
File ---> Open изменить.

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#109]
У нас есть open binary и custom open. Режим Open если я правильно помню относится к старым наблюдениям с разным количеством каналов. Предлагаю в меню перетасовать строчки: на первом месте open binary (чаще всего используется) и переименовать его в open binary BSA3, на втором месте вместо  open  поставить open RK8 BSA1/3, на третьем месте вместо custom open поставить open RK16 BSA2/3.

**Comment by vtyulb** [comment]
Сделано
