### ISSUE TITLE
Правка названий

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#111]
в названиии "Investigation of pulsars" пропущено "l"
в этом же блоке заменить "precise search" на "testing of pulsars". Потому что этот  "precise search" ниже выступает как один из трех фильтров. Внизу его не менять.
Повыше серого пункта "precise timing" ввести пункт "Estimation of flux density". В этом блоке будут два фильтра "Integral flux", "Rotation Measure" как и договаривались

**Comment by vtyulb** [comment]
partially done
