### ISSUE TITLE
Дополнительные фильтры

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#112]
Нужно в режимы Investigation of pulsars и Non pulsar flux ввести дополнительное окошко, куда можно поставить галочку. Название фильтра "Чистка помех". По умолчанию этот фильтр нажат, т.е. в нем стоит галочка. Если его отжать, то не нужно делать чистку помех в данных при оценке плотности потока. Этот режим нужен для мерцающих источников у которых ты убиваешь мерцания и для сильных пульсаров у которых видны отдельные импульсы, которые ты срезаешь.

Фильтр работает лишь когда оценивается плотность потока!!!

**Comment by vtyulb** [comment]
Чистки помех при определении плотности теперь нет
