### ISSUE TITLE
Калибровка по ступеньке, перенарезка длинных и коротких данных 

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#121]
Поиск ступенек, оценка их высоты в единицах температур.
До 2013 года ступеньки были довольно произвольными по времени. После этой даты запуск шести ступенек в сутки проводится в одно и то же московское время и общая длина ступенек примерно одинаковая. 5 секунд длительность первого минимума, 5 секунд максимум, 5 секунд второй минимум. Точность запуска плюс минус 0.5 секунды. Номера часов где находятся ступеньки в верхней и нижней площадках: первый час (пример названия файла 010416_01_N*****.pnt/pnthr), час 05, час 09, час 13, час 17, час 21, начиная с даты 11 октября 2013 года. Для уборки краевых эффектов усреднение шумовой дорожки на ступеньке для коротких данных проводится в первом минимуме точки 3025-3060; в максимуме точки 3075-3110; во втором минимуме точки 3025-3160. По первому и второму минимуму определить среднее. Длинные данные пишутся с 2014 года и поэтому для них ступеньки всегда в одних и тех же местах. Первый минимум 24225-24425; максимум 24640-24840; второй минимум 25035-25235. После получения соответствующих усредненных значений нулей ступеньки и максимума ступеньки в каждом частотном канале проделываем следующие процедуры:
 
1) Для выравнивания каналов по частотам подбираем такие коэффициенты, чтобы после домножения данных в каждом канале на такой коэффициент его высота в единицах АЦП была константой. Назовем эти коэффициенты k1,k2…k6(или k32).
2) Делаем тоже самое со следующей по ходу времени ступенькой. Получаем еще 6 или 32 коэффициента
3) Предполагаем, что между ступеньками (т.е. в течении 4 часов) коэффициент усиления менялся линейно. Тогда зная расстояние по времени до середины блока мы можем домножить в каждом частотном канале вырезанного блока за данный день на такие коэффициенты, которые должны были бы быть в данном месте.

Значение высоты «промежуточной» ступеньки находящейся на источнике = (Высота первой ступеньки – Высота второй ступеньки) **умножить** (расстояние от первой ступеньки до источника в часах и долях часа **деленное** на четыре) **прибавить** Высота первой ступеньки. 

4) Нужно иметь в виду, что нарезка начинается с какой-то даты. Именно какая-то перваая ступенька из этой даты и будет базовой. Ее высота как и у всех прочих ступенек равна 2100 градусов, но самое главное, что ее высота в единицах АЦП должна стать как бы базовой константой для всех ступенек с которыми мы будем работать. Более того, если у нас появятся дополнительные данные, которые мы захотим добавить нужно будет где-то сохранить высоту этой ступеньки в единицах АЦП для дальнейшей правильной нормировки.

Желательная вещь: Делать одновременно перенарезку как длинных, так и коротких данных сразу во всех 96 лучах.

Из видимых неприятностей только одна. Если по каким-либо причинами не записан час, когда у нас была ступенька или произошел сбой во время прохождения ступеньки, или в этот момент проводились тестовые работы и генератор ступенек был отключен, то ступеньки в записи в ожидаемое время не будет. Этот случай нужно как-то научиться отслеживать. Быть может по разнице высот у точек, отличающихся на 5 секунд по времени, если файл с соответствующим часом записан. Если такой случай произошел, то пользоваться значениями следующей ступеньки.

**Comment by vtyulb** [comment]
Ступеньки ищутся автодетектом, нарезка верхней площадки досчитается в ближайшие сутки-двое. Длинные данные хотелось бы считать на нормальном сервере.
