### ISSUE TITLE
Сложение средних профилей за много дней

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#128]
В режиме "Investigation pulsars"-->"Precise Search"-->"Single Period" предусмотреть возможность складывания средних профилей за много дней на какой-то фиксированной мере дисперсии.
Я представляю это как дополнительную галочку, которая неактивна, пока не нажат "Single Period". Если же он нажат, то при нажатии новой галочки работает режим сложение импульсов за разные дни, если эта новая галочка не нажата, то режим "Single Period" работает по старому. При новой работе "Single Period" необходимо, чтобы в окошке "Dispersion" была указана мера дисперсии на которой будет производится дальнейшее сложение средних профилей за много дней. Таким образом средний профиль образуется на фиксированном значении меры дисперсии и на фиксированном значении периода. Основное время будет идти на считывание файла. Для этой мера дисперсии должна быть возможность указать ее с точностью до десятых долей и ее значение может быть трехзначным (т.е до меры дисперсии 999.9). Соотвественно и при сложении среднего профиля нужно учитывать, что мера дисперсии указана до десятых долей. Дальше после первой обработки "Single Period" нужно всплывающее окно или какая-то другая возможность указать новый файл для сложения средних профилей или для прекращения этой работы или сделать также как для режима сложения SNR/DM. На экран выводить  двойной профиль (не знаю как лучше, сделать отдельный режим или использовать Pulsar analytics low memory), никакой шумовой дорожки на экран выводить не нужно. На нижней оси переделать оцифровку (эту же переделанную оцифровку использовать в режиме Pulsar analytics low memory). На оцифровке указать время в секундах и десятых долей секунды и если будет влезать, то и сотых долей секунды. Например, если пульсар имеет период 1 секунда, то его двойной период - это 2 секунды. На оси первая точка 0 секунд (начало записи), 2 секунды - конец записи и промежуточные значения в десятых долях секунды. Можно попробовать вариант, когда десятые доли секунды указаны, а сотые без подписи как штрихи.

**Comment by vtyulb** [comment]
Сделано аналогично графику SNR от дисперсии
