### ISSUE TITLE
Сложение динамических спектров за много дней

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#129]
Очень похожа на задачу 128 по сложению профилей за много дней.
В режиме "Investigation pulsars"-->"Precise Search"-->"Spectre" предусмотреть возможность складывания динамических спектров за много дней на какой-то фиксированной мере дисперсии.
Как и в задаче 128 дополнительную галочка, которая неактивна, пока не нажат "Spectre". Если же она нажата, то читается значение DM. После получения двойного профиля считается номер точки первого максимума (запоминается) и запоминается также какой сдвиг нужно сделать, чтобы  вершина первого максимума отстояла на четверть периода от начала среднего профиля. В исходных данных делается сложение в каждом частотном канале на фиксированном периоде (как это и было раньше), затем делается сдвиг такой какой мы запомнили для положения среднего профиля на четверть от начала окна, запоминается сам динамический спектр. После этого для дальнейшего сложения динамических спектров нужно всплывающее окно или какая-то другая возможность указать новый файл для получения динамического спектра. Возможно, что лучший вариант запоминать все эти динамические спектры в отдельных файлах, а затем производить их сложение.

**Comment by vtyulb** [comment]
done
