### ISSUE TITLE
баг сложение средний профилей.

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#136]
![default](https://cloud.githubusercontent.com/assets/11756008/23613279/dbf34eda-028f-11e7-8a6e-1ed4fcb9a3f6.png)
Пульсар не ищется, меры дисперсии в таблице пишутся произвольные. Работал с известным пульсаром J0048+3412; P=1.21709 (ATNF), P=1.21835 (наше определение). DM=39.9 виден в 13 и 14 блоке в лучах 4 и 5 (в 5 сильнее).

**Comment by vtyulb** [comment]
fixed
