### ISSUE TITLE
Баг сложения средних профилей

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#137]
1) На картинке видно, что импульсы в профилях большие, при этом SNR пишется меньше единицы.
2) Фон средней части картинки серый, а не белый. Нет возможности проверить разные меры дисперсии. При этом в самом начале запуска фон был белый. Серым стал, когда я загрузил третий каталог.
3) Не очень понятно, как происходит сложение средних профилей если в одном каталоге пульсар нашелся лишь на двух мерах дисперсии, во втором на 6, а в третьем на 8 разных мерах дисперсии.

Картинку прикрепляю
![default](https://cloud.githubusercontent.com/assets/11756008/23643406/a95b2794-0312-11e7-94ca-e937f2a98476.png)

**Comment by vtyulb** [comment]
1-2) Исправлено
3) Какая запись в таблице выбрана - та и будет складываться.
