### ISSUE TITLE
Возможная причина пропуска отчетливо видимых пиков

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#138]
4 sigma = 1/2 peak to peak.
peak to peak = full peak to peak -10% highest points

Это все работает, если на спектре мощности взят небольшой интервал (скажем 64 точки на коротких данных и 512 на длинных данных). После этого нужно выбросить 5% (или порядка того) самых максимальных точек на этом интервале, у оставшихся найти максимальное и минимальное значение, вычесть из максимума минимум, разделить на 4, умножить на 6 (т.е. в результате умножить на 1.5) и сказать, что получившееся значение равно 6 сигма шумов. Все что выше этого значения на этом интервале обозвать гармоникой. Затем брать следующие 64 (или 512) точек и все те же процедуры. Это нужно делать, т.к. дорожка неравномерная по ширине и такой способ позволяет с ней работать. 

Если ты работал на полном интервале (минус начало, где спектр мощности бежит вверх), то при наличии нескольких сильных гармоник шум будет определен неправильно и относительно слабые гармоники будут пропущены.

**Comment by vtyulb** [comment]
К стрелочкам приделан другой алгоритм чистки, а также снижен минимальный уровень детекта объектов. Остальное делается в задаче #133
