### ISSUE TITLE
Новый баг???

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#142]
При попытке в "Precise Search" посмотреть динамический спектр пульсара с периодом в 3 секунды в длинных данных, программа выдала спектр такой длины, что он не поместился на экране. Любые попытки сжать его в продольном направлении ни к чему не привели. Так независимых пикселей в 3 секундах всего 300 штук (или 600 т.к. все с двойным периодом), то причина этого непонятна

**Comment by vtyulb** [comment]
Это не баг, это фича. Окно не сжимается в целях красоты.
Поставил возможное сжати до 1024 пикселей в ширину в любом случае.
