### ISSUE TITLE
Скорость счета в "precise search"

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#143]
скорость счета в "precise search" уменьшилась в 2-3 раза. Теперь несмотря на два потока пульсар считается порядка 30 минут (было 15).

**Comment by vtyulb** [comment]
Сравнил текущую версию с версией октября 2016 https://github.com/vtyulb/BSA-Analytics/tree/a9bc028c64d4a8dd63f5e523a6b1e4a3fc704028
Скорость precise search на длинных данных совпадает с погрешностью в несколько процентов, причем новая версия быстрее. Проверено на периодах
0.447 (~4.67 секунды на линию)
1.789 (~12 секунд на линию)
4.789 (~29 секунд на линию)
 
**Can't reproduce**
