### ISSUE TITLE
Листание страниц в серой зоне

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#144]
Если загрузить "Full gray zone". то очень неудобно листать разные дни. Если есть возможность, то нельзя ли внутри этой желтой зоны при нажатии page down оказываться на следующем файле (дне), а при нажатии стрелка вверх или вниз проматывать все значения как обычно. Просто там порядка 3000 уникальных строк и в ручном режиме делать переходы через стрелочки вверх и вниз очень неудобно

**Comment by vtyulb** [comment]
Аналогично сделал и для белой зоны
