### ISSUE TITLE
Проверка перенарезки

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#154]
в нарезке нижней площадки блок 200 и соседние имеют меньше 200 файлов. Похоже на сбой. Проверить эти блоки при новой нарезке, так как в верхней площадке этого же блока почти 800 файлов, а наблюдения шли одновременно.

**Comment by vtyulb** [comment]
В новой нарезке, по крайней мере в этом блоке, все в полном порядке. Фильтр, который убирал файлы вырезан.
