### ISSUE TITLE
мелкий баг

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#155]
почему-то перестал подгружаться pdf  из help

**Comment by vtyulb** [comment]
Какой режим? Analytics / Fourier Analytics или обычный?

**Comment by STyulb** [comment]
Я пробовал подгружать help-->Handbook при просмотре бинарных файлов и 
при режиме pulsar search. Никакой реакции.


13.03.2017 16:13, Vladislav Tyulbashev пишет:
> Какой режим? Analytics / Fourier Analytics или обычный?
>

**Comment by vtyulb** [comment]
fixed
