### ISSUE TITLE
нарезка ступенек (напоминание, диск принесу)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#156]
проверил не все ступеньки, но
1) большая часть реально существующих ступенек почему-то неправильно вырезалась только в первом модуле во всех лучах. В результате там что-то вроде периодической помехи.
2) Что вырезала программа в 2013 году - это загадка, т.к. ступеньки там писались в том числе и в другое время.

**Comment by vtyulb** [comment]
Сейчас перешел на полный автодетект
