### ISSUE TITLE
замеченные баги в ступеньках

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#157]
1) Есть периодические пики, наблюдаемые лишь в первом модуле. Например, пик приходящийся на точки 111015_17 и 121015_17 отсутствует во всех модулях, кроме первого. Ступенька есть во всех модулях и она совершенно обыкновенная.
2) Маленькие пики и провалы в записи наблюдающиеся по всем модулям и лучам. Например пик за 290515_17, имеет величину больше единицы. Точки вокруг имеют уровень порядка 0.3. Если взять исходную записи и посмотреть реальную величину пика за этот день, то она равно 0.3. Т.е., пик ложный. Провал в записи за 260515_17 соответствует уровню около нуля. Там реально не писалась ступенька и поэтому значение "0" правильное, но нужно как-то это учитывать при нормировке данных. Предлагаю, что если за произвольные сутки писалась хотя бы одна ступенька, то нужно взять ее значение для калибровки. Пример: данные в 9 часов утра. Есть ступенька в 23 часа предыдущего дня и 23 часа этого дня. Нужно для калибровки взять ступеньку предыдущего дня. Если разрыв больше суток, то эти данные не калибровать, но сами данные должны остаться, так как можно работать с исходными записями при поиске пульсаров в индивидуальные дни.
3) отдельные провалы ничему не соответствуют. Например есть провал до нуля (т.е. ступенька не обнаружена) за 181115_09. При этом в записи ступенька есть. 
4) сильные пики в 2013 году. Например, очень мощный пик за 210713_09 по всем модулям и лучам. В этой записи ступеньки нет и должен писаться "0" для калибровки. Вообще говоря в 2013 году многие ступеньки писались в произвольное время и часто не писались вообще. Так как выкидывать 1.5 года слишком жирно, то нужно как-то научиться искать ступеньки в более менее автоматическом режиме. При этом нужно иметь в виду, что уровень сигнала может быть сильно разный за разные годы.
5) напоминаю, что существуют наблюдения в 5 модулях. Нужно исключить ступеньки, которые были в этих модулях.

**Comment by vtyulb** [comment]
В связи с переходом на полный автодетект, все проблемы исчезли
