### ISSUE TITLE
маленький баг в показе binary data

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#158]
В режиме показа исходных данных в правом нижнем углу пишется полное название директории откуда читаются данные. Это название не помещается и собственно имя файла отсутствует. Нужно это название разбить на 2 строки, чтобы все помещалось.

**Comment by vtyulb** [comment]
Не воспроизводится, проверь что у тебя последняя версия

**Comment by vtyulb** [comment]
Если баг и был, то теперь его точно нету
