### ISSUE TITLE
Дополнительная задача к нарезке данных

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#162]
Очень желательно при нарезке для блоков, модулей, лучей и частот считать сигму шумов блока, по которому идет нарезка, по классической формуле 

summa(I-<I>)**2/<I>**2

Сигма шумов должна считаться для блока после срезания сильных помех. После подсчета всех сигм выстроить их в порядке возрастания даты и записать это значение и дату точки. По моим оценкам получится файл размером порядка гигабайта для каждой из площадок. Вывод на экран сделать для содержимого одного блока (т.е. это порядка 1000 значений сигмы шумов за все посчитанные дни). По вертикальной оси получится величина шума, а по горизонтальной оси дата. Если нормирование по ступеньке будет плохим, то это сразу будет видно. Если нормирование будет хорошим, то такой файл позволит мне контролировать блоки, вызывающие сомнения и проверять почему я не вижу известные пульсары.

**Comment by vtyulb** [comment]
done
