### ISSUE TITLE
Поиск отдельных импульсов (база данных)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#164]
Сделать программу для поиска импульсов, имеющих какую-то меру дисперсии. Хорошо бы, чтобы тестовый вариант реально работал в текущей программе. Сейчас это не работает. При этом есть куча сильных пульсаров на которых легко проверить методику поиска. Смысл у задачи очень близкий к поиску гигантских импульсов. Но делается перебор мер дисперсий в очень широких пределах и смотрится появляются ли новые достаточно короткие по длительности сигналы у которых вырос SNR по крайней мер в 2 раза (после нормировки ступенькой) или в 1.5 раза по текущему положению

**Comment by vtyulb** [comment]
А это задача, внезапно, оказалась поиском транзиентов и FRB. Это уже сделано
