### ISSUE TITLE
баг картинки

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#165]
Уже говорил об этом баге: 
1) Внизу картинки виден обрезанный адрес. 
2) Почему-то не воспроизвелось склонение источника, которое должно отражаться при выведении исходных бинари файлов.
![default](https://cloud.githubusercontent.com/assets/11756008/24045813/67bb04ea-0b31-11e7-97fc-c908edb887ba.jpg)

**Comment by vtyulb** [comment]
Конкретно полное имя файла я пофиксил. Но вообще, в режиме Analytics, надо пользоваться функциями Analytics, а не побочным наследством чтения файлов, генерации звуков и т.п.
