### ISSUE TITLE
Правильное сложение спектров мощности

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#171]
Для обеспечения максимального отношения сигнала к шуму в конечном сложенном файле спектра мощности нужно сделать следующие процедуры:
1) Выстраиваем все сигма_i шумов в 7ом (или 33) канале данного блока, модуля, луча в порядке возрастания. (Для каждого модуля, луча и блока работа повторяется). 
2) Делим все значения на первое (минимальное) значение шума. Получается ряд чисел от единицы и больше.
3) Вычисляем ряд, который определяется следующей формулой:
степень увеличения SNR=N/(корень из (сумма от возводимых в квадрат сигма_i_шума))
т.е. первый член у нас автоматом равен единице. Если второй член ряда имеет сигма шумов единица, как и первый член, то увеличение SNR будет корень из 2, если шум будет больше, то увеличение SNR будет меньше, чем хотелось бы. N в формуле - это количество складываемых членов ряда, i- текущее значение.

Первый член ряда SNR состоит из одного сигмы шумов.
Второй член ряда SNR состоит из вычисленой суммы квадратов двух сигмы шумов (первой и второй) и   корень из этой суммы
Третий                                       из вычисленной суммы квадратов трех сигмы шумов (первой, второй и третьей) и корень из этой суммы
               и так далее, пока не сложатся все сигмы шумов
4) Эта зависимость имеет максимум. Этот максимум соответствует какому-то номеру i. Например, пусть для данного блока, модуля, луча выяснилось, что максимум соответствует точке 800 из 1200 имеющихся оценок сигмы шумов. Смотрим из пункта 1) какое сигма шумов соответствует номеру 800. В программе сложения спектров мощности задаем сложение всех спектров мощности у которых в исходных посчитанных нами шумах сигма_шумов меньше или равно сигме_шумов в точке 800. Если есть возможность, то предусмотреть вывод на экран вычисленного ряда из пункта 3). По нижней оси номер точки, по верхней оси подсчитанное значение выигрыша SNR. Если возможности нет, то выводить где-нибудь на оставшемся пока пустом месте SNR=число. Это удобно для работ по вычислению реальной чувствительности методики по сложению спектров мощности.

**Comment by vtyulb** [comment]
Сделано
