### ISSUE TITLE
Поиск сильных транзиентов со средними мерами дисперсии и одиночными всплесками

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#197]
Если у нас найден реальный импульс от пульсара, то в динамическом спектре должен быть виден наклон. Опыт показывает, что полоска в динамическом спектре видна если сигнал шум в исходной записи больше 6. Одиночный всплеск подразумевает, что за время наблюдений на вершине диаграммы мы видим так мало импульсов, что период через спектр мощности не восстанавливается.
1) Выбираем те записи, которые хорошие. 
2) Перебираем DM от 2 до 200. Для каждого сдвига проверяем появились ли пики в проверяемой зоне. Если появились, то больше ли их величина, чем была в 33 канале в соответствующей точке. Проверяем увеличился ли SNR в пике в 2 и более раза  (в норме увеличение может быть в 5 и более раз) по сравнению с тем, что там было раньше. Это прямой поиск похожий на то, как мы искали пульсары в самом начале.
3) Находим пики с SNR>6. Запоминаем значение DM, SNR пика, блок, модуль, луч.
4) Тест по известным обычным пульсарам и пульсарам с одиночными всплесками (RRATs).
5) Для проверки должна быть возможность строить динамический спектр для обнаруженных кандидатов.

**Comment by vtyulb** [comment]
Все сделано. Для того чтобы внести транзиент в список "известных пульсаров" следует придерживаться стандартного формата. Вместо периода объекта нужно ставить *, например
#just another transient
4 6 * 19:20:00 No visible period

Установка дисперсии пока не поддерживается
