### ISSUE TITLE
Поиск транзиентов, отсеивание ненужного

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#199]
1) Не нулевая DM. За исключением поиска с нулевыми DM.
2) Повторяемость времени начала сигнала не более чем в 2 или в  крайнем случае 3 лучах
3) При сложении вспышки по каналам c учетом DM должен расти SNR.
4) Общий SNR должен быть больше 7.
5) Если наблюдается форма рассеянного импульса, то это большой плюс
6) Регулярная повторяемость на одном и том же месте на небе по звездному времени.

Эти признаки можно включить, по возможности, в виде фильтров или большей частью сразу в поисковую программу с тем, что если эти признаки не проходят, то и заносить эти источники в таблицы не нужно.

**Comment by vtyulb** [comment]
В каком-то виде уже реализовано
