### ISSUE TITLE
дополнение к задаче 198.

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#201]
Нужно делать не только кросскорелляцию не 1 с 2, 3 с 4 и т.д., а затем сложение 16 CCF (это хорошо для больших DM), но и кросскорелляцию 1 частотного канала с 17, 2го с 18, 16го с 32, а затем сложение. Второй вариант будет хорошо работать с малыми DM (от DM 3-4 и до DM 30-50).

**Comment by vtyulb** [comment]
Перенесено в #198
