### ISSUE TITLE
для внешних любителей искать пульсары

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#203]
Судя по всему как бы мы не извращались поиск транзиентов может быть с пропуском реальных объектов (начиная с того, что ты пропускаешь 10 секунд после того как нашел помеху). В то же время глазами можно легко увидеть в динамическом спектре наклонную линию если она есть. Предлагаю для внешних любителей поискать:
1) Предварительно подготовить несколько картинок динамических спектров с тем, чтобы было понятно, что ищется
2) Сделать для любителей вывод на экран картинки динамического спектра длительностью примерно минуту сразу в нескольких лучах. Думаю, что на экране поместиться один модуль без проблем. 
3) Если человек что-то такое увидел, то нажимает кнопку SAVE и для нас сохраняется модуль, луч, дата, время. Все легче потом просмотреть предварительно отобранных кандидатов...
4) Нужно сверху экрана (или в любом другом месте) пустить строку в которой указаны те пульсары или те транзиенты, которые уже были найдены ранее в это звездное время (т.е. в ту минуту, которая отражена в виде динамического спектра на экране). Файл с этими пульсарами и транзиентами пополняемый и пополняем мы его сами.
5) Для любителей поиска пульсаров картинки на экран должны выводится все время новые. Если реально отобразить одну минуту и один модуль на экране, то за сутки генерируется 17280 картинок, за 3 года нужно умножить на 1000. Я лично за неделю просматриваю порядка 30000 картинок, т.е. сотня любителей за год просмотрит все накопленное "непосильным трудом" не напрягаясь.
6) Желательна предварительная подготовка перед выдачей картинок: а) выводить лишь те записи, которые мы определяем в качественные; б) в частотных каналах посрезать явные пики. Уровень срезаемого нужно подобрать. Это делается для того, чтобы помехи не были "слишком черные" по сравнению с возможным транзиентом. Как мы знаем общий сигнал шум 10 более чем достаточен, для того чтобы отчетливо увидеть линию.

**Comment by vtyulb** [comment]
На выборке найденных FRB хорошо понятно, что на длинных спектрах ни черта не видно. Это означает увеличение числа картинок на пару порядков. Объем данных и вычислительная сложность вполне вероятно превзойдет обычный поиск, что делает задачу бессмысленной. 

Думаю после полной обработки данных можно будет отдать найденную выборку любителям, и дать доступ к нашей базе, тогда нам дополнительно найдут что-нибудь еще.
