### ISSUE TITLE
дополнительный фильтр (задачи 197, 198, 199)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#204]
Если пик одновременно виден кроме двух ближайших сверху и снизу лучей в этой же точке по времени в других лучах, то можно его не исследовать, а сразу выкидывать.

**Comment by vtyulb** [comment]
> Для транзиентов с малой мерой дисперсии нужно сразу делать проверку есть ли этот пик более чем в 2 лучах независимо от модуля. Если есть, то выкидывать этот случай сразу и никуда не записывать.

**Comment by vtyulb** [comment]
done
