### ISSUE TITLE
поиск RRATs (баг???)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#209]
Слава, проверь, пожалуйста, соответствует ли длина "среднего профиля" транзиента его длине в динамическом спектре. В тех блоках, где есть длинные динамические спектры (файлы без транзиентов) создается ощущение, что выводимый "средний профиль" сильно короче и не соответствует видимому спектру. Т.е. есть спектры, где явно должно быть два пика (согласно потемнениям в спектре), а на среднем профиле один пика... Например такая ситуация есть в блоке 131 (сделать усреднение по 10 точек).

**Comment by vtyulb** [comment]
1) Длина соотвествует точно
2) Один или два пика на графике - shit happens, в чем дело не знаю, но думаю что все в порядке
