### ISSUE TITLE
Поиск RRATs (работа после обнаружения)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#210]
Если мы приняли решение, что RRATs обнаружен, то теперь нужно выявить его повторяемость и  точную UT координату импульса. Нужна работа с индивидуальными записями.
1) Задаем модуль, луч, меру дисперсии, центральную координату, период поиска (например, за данный месяц, или за несколько дней или за весь период наблюдений). Проверять нужно все данные, по которым мы сами проводим поиск обычных пульсаров. Сейчас программа поиска выкидывает целых 6 часов за сутки только потому, что там есть ступеньки. Программа же индивидуальной обработки вполне может работать с этими записями.
2) Складываем все частоты внутри выбранного луча с учетом заданной меры дисперсии.
3) Ищем **все** пики в полученной записи в пределах плюс минус 2 минуты от заданного центрального времени на уровне сигнал к шуму 5 (т.е. никаких пропусков 10 секунд после обнаружения пика).
4) Для каждого найденного случая запоминаем полные UT координаты, номера точек максимума в профиле, SNR
5) Берем следующую дату и т.д. по пунктам 2)-4)
6) Для статей очень важен параметр обнаружимости. Т.е. статистика такого рода: сколько реально записей (дней) проверялось, сколько обнаружено индивидуальных импульсов, в каких блоках обнаружено несколько импульсов (с учетом пункта 4, эта информация позволяет хотя бы в грубом виде восстановить период), 
7) Эта же часть программы должна позволять складывать динамические спектры. Так как мы знаем координату вершины "среднего профиля" на самой низкой частоте для разных импульсов одного дня или за разные дни, мы можем совместить вершины и поканально сложить записи за разные дни. Единственная проблема в том, что программа может создать записи немного разной длины и нужно их все подогнать под самую короткую запись.

**Comment by vtyulb** [comment]
1) Последнии версии поисковика проверяют все подряд
3) Пропускается всего лишь секунда
6) Считаются все дни, и пропуски делаются в рамках статистической погрешности
7) Спектры вполне складываются, в том числе и с разными дисперсиями
