### ISSUE TITLE
проверка багов (поиск транзиентов)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#211]
1) в директориях, хранящих обработку имена файлов выглядят 4-значными. Сейчас обработано 3 дня и уже есть директории, где больше 100 файлов. При неудачном раскладе за месяц в таких директориях будет больше 1000 файлов, а за год больше 10000. Не возникнет ли проблема с нумерацией.
2) Программа вписывает неправильную UT дату в шапку. Обрабатывается сентябрь, название файла правильное, а в UT стоит октябрь.

**Comment by vtyulb** [comment]
1) В случае, если файлов будет более 10000, работа с ними вручную не предполагается
2) UT шапка нужна только в целях совместимости. Там специально подобранное время, чтобы первая точка соотвествовала времени 00:00:00, ну или как-то так. Так что в случае необходимости, исходный файл надо брать из поля native_datetime
