### ISSUE TITLE
Загрузка транзиентов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#217]
Желательно сделать две процедуры, реализованные для белой зоны стандартных пульсаров. А именно:
1) При начальной загрузке блока сделать сортировку по модулям и лучам. Т.е. все транзиенты должны выводится от 1 модуль 1 луч, до 6 модуль 8 луч. Если каких модулей и лучей не будет, так и бог с ними.
2) Хорошо бы сделать листание до следующего луча через Page Down. Если вдруг ясно, что с этим лучом ловить нечего, то и сразу можно его перелистнуть на следующий. Это будет удобно.

**Comment by vtyulb** [comment]
Это вроде бы еще неделю назад сделал
