### ISSUE TITLE
Поиск RRATs на малых мерах дисперсии (задачи 196 и 204)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#218]
**К задаче 204**
Для транзиентов с малой мерой дисперсии нужно сразу делать проверку есть ли этот пик более чем в 2 лучах независимо от модуля. Если есть, то выкидывать этот случай сразу и никуда не записывать.
**К пункту 5 из задачи 196.**
Для пиков, которые обнаруживаются не более чем в 2 лучах на SNR>6 вести статистику в отдельном файле. Этот файл должен изменяться (пополняться), когда проводится счет очередных данных. В файле должна быть следующая информация для каждого блока:
1) дата, когда найден пик 
2) имя файла
3) модуль и луч
4) сколько пиков найдено в этом модуле и луче за эту дату
5) сколько дней просчитано (т.е. не выкинуто, а реально посчитано, пусть даже за данный день не найдено ни одного пика)
6) сколько пиков в найдено в данном модуле и луче за все посчитанные даты

При загрузке этого файла на экран должно выводится 48 точек (гистограмма). Значение в каждой точке - это количество найденных импульсов, удовлетворяющих поставленной задаче. При подводе курсора к точке должна появляться информация в любом удобном месте: 
1) Количество импульсов
2) Модуль и луч
3) Количество просчитанных дней см. выше
4) номер блока

**Comment by vtyulb** [comment]
перенесено в соответствующие задачи
