### ISSUE TITLE
упрощенный поиск транзиентов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#219]
То же, что и для длинных данных, но на коротких. Единственная разница начинать поиск DM от 10 и вести до 100 с шагом по DM=5. Все получится грубее, чувствительность похуже, зато посчитать и посмотреть можно будет быстро!!! + методику легче отладить.

**Comment by vtyulb** [comment]
Очень не хочется плодить лишние сущности. На длинных данных все кое-как работает. Тестовые выборки делаются быстро. На коротких данных будет другой спектр проблем, решение которых будет бесполезно для длинных данных.
