### ISSUE TITLE
поиск дупликатов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#22]
В программе поиска дупликатов (и, естественно, в analytics) нужно ужесточить условия подтверждения того, что дупликат найден. 
1) Оставить в ходе поиска проверку лишь для половинных периодов, двойных и тройных. За основной период принимается период введенный в специальном файле или в поисковом активном окошке.
2) Условие подтверждения дупликата для коротких данных следующее:
модуль(дробная часть от [кратный период/главный период] * целая часть от [длина записи (200сек)/главный период])<0.1*Period_Pulsara - дупликат найден!!!
если 
модуль(дробная часть от [кратный период/главный период] * целая часть от [длина записи (200сек)/главный период])< 1.5*постоянная времени, то использовать именно это условие

**Comment by STyulb** [comment]
Слава, привет!
Ты слишком рано сделал архив за 020914, т.к. там был сбой и не посчитан 
час 00. Его придется заново запускать и считать.
       Пока,
             Папа

05.04.2015 18:22, Vladislav Tyulbashev пишет:

**Comment by vtyulb** [comment]
Так я не могу его посчитать, так как падает на нем все. Отложен он пока

--
С уважением,
Владислав Тюльбашев.


09.04.2015, 18:49, "STyulb" <notifications@github.com>:

**Comment by STyulb** [comment]
o'k
Тогда я перекачиваю этот архив. Обойдемся без его счета.
     Пока,
              Папа
P.S. Спасибо за кнопку "левые" пульсары. Пока ничего не проверял. 
Сегодня надеюсь закончить поиск пульсаров с SNR>6 и установлю последнюю 
сборку.

09.04.2015 20:14, Vladislav Tyulbashev пишет:

**Comment by vtyulb** [comment]
Я его удалил уже...
Через пару часов создастся.

--
С уважением,
Владислав Тюльбашев.


10.04.2015, 08:42, "STyulb" <notifications@github.com>:
