### ISSUE TITLE
работа с известными транзиентами

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#223]
фильтр "Не показывать известные транзиенты"
1) Запись в уже существующий файл с известными пульсарами, но сделать блок транзиентов ниже и для транзиентов информация следующая:
Вначале имя пульсара или нового открытого нами транзиента, затем: блок, модуль (или модули через запятую), луч (или лучи через запятую), мера дисперсии (или меры дисперсий через дефис: т.е. от DM такой-то до DM такой-то). С мерами DM придется заморачиваться, потому что есть вероятность открыть на разных мерах DM в одном модуле и луче разные разные транзиенты. Такая ситуация была неоднократно при поиске пульсаров, когда в одном блоке, модуле, луче было сразу три пульсара.
2) Если фильтр включен, то известные (в том числе и уже найденные нами не показываются в выходной таблице).

**Comment by vtyulb** [comment]
Сделано
