### ISSUE TITLE
Помехи в транзиентах 0

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#224]
Поиск транзиентов классическим образом, по динамическим спектрам
1) Фильтры "до"
а) поиск начинать от DM=3 и вести до DM=100
б) в случае широкой по времени помехи, она будет отражаться как найденный транзиент на разных DM. Такие помехи можно обнаружить из их повторяемости во многих лучах. Т.е. задать уровень SNR=5-6, если в нескольких лучах на DM=0 есть сигнал, то не рассматривать первую точку как начало учета DM и сложения импульса в каналах. Затем проверять точку 2, если опять сигнал c уровнем SNR>5-6 в нескольких лучах, то не строить для этой точки разные DM.
2) Фильтры "после" (пытаемся убрать самые частые случаи "помех" - будем добавлять новые фильтры по мере проверки того, сколько остается сигналов на выходе)
а) импульс образован сигналом всего в нескольких частотных каналах. Нужно подобрать какой-то критерий, что в суммированном по канале импульсе должно участвовать не меньше 10-15 частотных каналов. Возможно эта проблема большей частью разрешиться после того, как сделаем нормировку каналов по ступенькам

**Comment by vtyulb** [comment]
done
