### ISSUE TITLE
к рисункам транзиентов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#225]
1) В крайней правой вкладке (где цвет импульса можно менять) дополнительно выводить звездное время импульса (с точностью до секунды) и UT time импульса с точностью до точки (или долей точки).
2) На рисунке выводимом на печать у тебя есть вкладка с информацией ту да же добавить звездное время импульса и его UT time

**Comment by vtyulb** [comment]
done
