### ISSUE TITLE
работа с транзиентами "после"

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#228]
1) Как ни старайся, но наверняка останутся плохие дни, которые дают гигантское количество плохих файлов, не исключаемых фильтрами. Предлагаю ввести новый фильтр, который по умолчанию всегда включен. Для работы этого фильтра в файле помех (или новом файле) содержится информация вида: блок и дата (т.е. нужно иметь возможность вносить в этот файл информацию). Если при поиске очевидно, что этот блок за этот день плохой, то посчитанные результаты просто не показываются. По моим оценками один неудачный день в блоке может сгенерить несколько тысяч записей.
2) Сложение динамических спектров и профилей хороших дней. В продолжение твоей идеи о сложении всего, что прошло фильтры (т.е. создании "белой зоны") предлагаю, чтобы имелась также возможность сложить лишь те даты, которые выбрал сам. Все-таки в общем случае глаз точнее отбирает нужные файлы.

**Comment by vtyulb** [comment]
1. Фильтр плохих дней теперь работает на этапе предобработки.
2. Сложение выбранных спектор работает через Mem/M+. Сложение всех спектров еще сделаю, это отдельная задача #227
