### ISSUE TITLE
на будущее (создание лайт версии транзиентов)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#229]
Судя по всему большая часть объема каталога будет состоять из "не убираемых" помех. Тех самых для которых я написала, чтобы была возможность не показывать на экране отдельные дни в просматриваемом блоке. Тем не менее показывать он их не будет, что правильно, но грузить то он их будет все равно. Сейчас у меня на отдельные блоки загрузка доходит до минуты. Это при обработке одного месяца. За 3 года можешь посчитать сам какие потери времени при загрузке тех или иных блоков. Более того, может быть ситуация, когда оперативки (особенно на слабых компьютерах) просто будет не хватать.
Предлагаю: иметь полную версию каталога, естественно со всеми ранее оговоренными фильтрами и возможность создания лайт версии в которой учитываются выкинутые руками дни в блоках как для помех, так и для уже найденных пульсаров (которые тоже прописаны в соответствующих таблицах). Это позволит сильно сократить объем просматриваемого материала)

**Comment by vtyulb** [comment]
Задача замещена на #231
