### ISSUE TITLE
белая зона транзиентов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#246]
неожиданно в белой зоне стали видны все модули и лучи, включая те, где нет ни одного обнаружения. Это неудобно.

Предлагаю сделать так, чтобы в белой зоне показывались лишь те модули и лучи, где есть 2 обнаружения и больше (а еще лучше сделать это параметром, который по умолчанию 2, а так в окошечке можно поставить, например, 10 и он выдаст все источники, которые определились больше 10 раз)

**Comment by vtyulb** [comment]
Сейчас проверил - в последней виндовой сборке все работает корректно. На всякий случай перевыложил ее
