### ISSUE TITLE
сложение динамических спектров с разными DM (на будущее???)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#247]
Часто встречается ситуация, когда в один день слабый транзиент определился на одной мере дисперсии, а в другой день на другой (близкой) мере дисперсии. Так как программа автоматически ставит максимум всегда в одну точку, то в принципе эти разные динамические спектры можно сложить, если убрать "лишние" пикселы с конца динамического спектра, который длиннее (имеющий большую DM). Реальная мера дисперсии всегда одна, так что процедура абсолютно нормальная.

**Comment by vtyulb** [comment]
Сделано
