### ISSUE TITLE
баг нахождения транзиентов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#248]
У нас есть в статье источник J1458+1724,  блок 263 модуль 1, луч 8 (немного проглядывает) в модуль 2 луч1. 

Этот источник есть в старой обработке сентябрь нижняя площадка и исчез в новой обработке (тем временем он стоит в публикуемой работе)

**Comment by vtyulb** [comment]
Очень хреново виден объект, от помехи отличается слабо. Соответственно, новым фильтров подобное убирается как помехи
