### ISSUE TITLE
Поиск ширины импульсов транзиентов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#254]
После того, как найдены кандидаты в транзиенты нужно их исследовать. Среди прочих характеристик есть так называемая ширина и полуширина импульса. Сейчас я это измеряю прямо на экране мышкой, что неудобно. Предлагаю:
1) Задается блок, модуль, луч, дата, предварительная мера дисперсии (найденная программой)
2) В заданном вновь проводится поиск на пониженных SNR (думаю, что на тройке или четверке будет нормально). Если это быстро, то проверяются все меры дисперсии, если долго, то плюс минус 5 единиц от заданной меры дисперсии. Для каждого найденного транзиента в таблицу выводится его координата в точках на данной мере дисперсии.
3) Строится зависимость: SNR/DM для всех найденных импульсов
4) Проводится усреднение в записи, по 2, 4, 8, 16, 32 точки. Для каждого усредненного массива для наилучшей найденной DM строится зависимость SNR/от количества усреднненных точек. Первая точка в зависимости - это вариант, когда нет усреднения.

**Comment by vtyulb** [comment]
Сделано
