### ISSUE TITLE
Оценка периода (отдельный режим).

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#255]
Отдельно и ни с чем не связанное окно (новый режим работы)
1) Задаются координаты вершин в точках всех найденных импульсов за день (их может быть несколько)
2) Если дней несколько, то нужно иметь возможность задать дополнительные координаты вершин импульсов в точках в других днях
3) Вычисляются все возможные разницы (только внутри одного дня!!!) между вершинами в точках.  Например координаты вершин 1000, 501, 102, тогда разницы в точках будут 499; 898; 399 и других разниц нет.
4) Для каждого дня строится зависимость: Расстояние между точками делить на 2; 2.5; 3 и так далее пока получаемое число не станет меньше 16. 16 - это минимальное значение массива по умолчанию (нужно иметь возможность его менять). Например: в первый день у нас было 3 импульса, во второй 2, в третий 2. Тогда у нас окажется 3 массива за первый день и по одному за второй и третий дни. Всего их будет 5.
5) Строится новый массив с шагом в одну точку. Максимальная точка массива по умолчанию 1200 (нужно иметь возможность ее менять). Первые 16 точек массива - это нули. 
        Далее проверяется точка 17. Берутся все массивы из пункта (4) и если в точку 17 (т.е. в значения от 16.5 до 17.5) попало лишь одно значение делимого, то в массиве пишется "0". Если в точку 17 попало два вычисленных значения из пункта (4), то из максимального числа вычитается минимальное, делается процедура (1/x) и полученное запоминается. Если в ячейку попало 3 значения, то из максимального вычитается меньшие числа, полученные значения перемножаются и делается процедура (1/x). В результате если мы попали на правильный период, то точка, в которую попало максимальное количество чисел из пункта (4) будет иметь следующие свойства. Все полученные разницы будут меньше 1. При перемножении (если чисел несколько) полученное число будет минимальным, а после (1/x) максимальным. 
6) Выводим на рисунок полученный массив. Максимумы в этом массиве будут говорить о возможных периодах. Нижняя ось на этом рисунке в точках. При наведении мышки на любую точку массива должен выскакивать период. Он равен координате вершины умноженной на величину отсчета (т.е. умноженной на 12.4926/1000). Тогда результат будет в секундах.

Тестирование: 
1) Задать отрезки длинной 2154 точки и 6837 точки. Найти периоды. Ответ: минимально возможный период 359.4 точки (у тебя это будет 359 или 400).
2) Задать номера вершин импульсов: 181509; 182953; 196765; 197894; 198889. Вычисленный период оказывается 141 точка (1.761 секунды)

**Comment by vtyulb** [comment]
В текущем виде период выдается в точках. Когда ты согласишься с тем что все работает, переставлю на выдачу периода в секундах
