### ISSUE TITLE
Оценка корректной меры дисперсии транзиента.

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#256]
Работа начинается при нажатии дополнительной галочки в режиме исследования транзиентов. В дополнительном окне задается предварительная мера дисперсии и вычисляются следующие значения:
Delta t_i = 4.1488 * 10^6 * (1/nu1^2 - 1/nu2^2) * DM,
где nu1 - это меньшая частота у частотного канала, а nu2 - это большая частота в мегагерцах. В нашем случае nu1=109.039, а nu2=109.117 МГц. Так как у нас 32 частоты, то мы можем вычислить 31 значение Delta t_i. Все они вычисляются между соседними частотами. Накладываем эти точки на рисунок динамического спектра. Первая точка между первым и вторым рядом пикселей отступив на 10 пикселей от вершины транзиента в сложенном профиле импульса. Вторая точка прибавив значение Delta t_2. Третья точка прибавив к полученному Delta_t_3 и так далее. Все точки соединить ясно видным цветом. При изменении DM в окошке кривая будет пересчитываться. Таким образом я увижу, что параллельно динамическому спектру на расстоянии 10 пикселей от него ездит кривая. Как только все точки этой кривой будут на одинаковом расстоянии от реального спектра, реальное DM определено.

Не знаю нужно тебе это или нет, но первая часть формулы до множителя DM - это 31 константа для каждых двух соседних частот.

**Comment by vtyulb** [comment]
Сделано
