### ISSUE TITLE
Долгий счет по длинным данным

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#26]
Слава, не знаю что ты поменял, но в результате этой работы во-первых, на каждом ядре время счета составляет 1 минуту (раньше было 20 сек), во-вторых, программа съедает от 97 до 99% всех счетных возможностей компа (из-за этого я вообще не могу работать на компе: ворд, интернет грузятся бесконечно долго)

**Comment by vtyulb** [comment]
Костыль вбит давно. Лучше уже не будет
