### ISSUE TITLE
оценка периода (дополнительные точки)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#262]
проверь дополнительно пульсары:
первый день 189773 194568
второй день  100450 111137
третий день 2445 16030
У меня получился период 266.6 точки

первый день 83990 86834 91890
второй день 278638 280692
У меня получился период 158 точек

Там где 6 импульсов за день я не смотрел все возможные разницы, так что там действительно вкралась ошибка, но совершенно однозначно период должен быть кратен 141 точка деленная на целое число.

**Comment by vtyulb** [comment]
Во втором случаеп период точно совпадает, в первом - один из возможных.
Текущая сборка выдает период в точках, можешь смотреть сам (точка 158 <=> период 158 точек)
