### ISSUE TITLE
динамический спектр (изменения)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#265]
Слава, для ряда пульсаров профиль импульса из динамического спектра получается обрезанным справа. Например, пульсар в Крабе: верхняя площадка, блок 98, модуль 6, луч 8. Предлагаю добавить сколько-нибудь пикселей справа, чтобы по крайней мере Краб влезал целиком.

**Comment by vtyulb** [comment]
Добавлено, заработает при следующем поиске
