### ISSUE TITLE
сбой в DM???

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#266]
Слава, посмотри низ за 6 месяцев, блок 7 м1, л3. Там явно видна глазом DM=2 или 3, а определяется DM=25.

**Comment by vtyulb** [comment]
Это не сбой, это меньше тройки, такие маленькие дисперсии не ищутся. Если посмотреть в спектре global, то видно, что в верхушке очень много энергии, на определенной дисперсии он явно цепляет пяток верхних точек, так что все в порядке. Такая ерунда хорошо срезается через trash days
