### ISSUE TITLE
падает программа

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#268]
1) Если работаешь с транзиентами и пробуешь калькулятор периодов, то он срабатывает один раз. Если снова потом поработать и вызвать его, то после того, как набиваешь числа и вновь запускаешь на счет программа падает
2) На картинке, которую выдает калькулятор, похоже есть сбой на одну цифру. Если навести мышку на вершину предполагаемого периода, то вместо правильного числа показывается на единицу больше.

**Comment by vtyulb** [comment]
fixed

**Comment by vtyulb** [comment]
Fixed again, итек торжественно заблочил гитхаб, и в процессе нестабильного коннекта испортился репозиторий, что я, конечно, не заметил. Пересобрал сборку
