### ISSUE TITLE
сбой периодов?

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#270]
Слава, считал очередные периоды. Точки 14902 15283 16495 20873. Получил период примерно 4.98с. При этом время между первой и второй точками = 4.76с. Это очень большая разница и я не понимаю откуда она взялась.

**Comment by vtyulb** [comment]
С очень большой вероятностью это значит, что период значительно меньше (0.226с)
Я разницы 4,759757 19,901030 74,594509 15,141274 69,834752 54,693478 поделил,
на этом периоде ошибка не более 5%, что, в общем-то, - одна точка.
