### ISSUE TITLE
определение периода транзиента

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#271]
для транзиентов, которые видны часто очень тяжело искать повторные импульсы за одни и те же даты. Предлагаю помимо ручного режима (его оставить и не трогать!!!) иметь автоматический режим поиска периода по нажатию галочки. 
Ввод: блок, модуль, луч, дисперсия. 
Работа: поиск всех импульсов, попадающих на одни и те же даты
Вывод: Рисунок с определением периодов
Проверка: нижняя площадка,  Блок 328, модуль 3, луч 2, дисперсия 17. В ручном режиме получил период 2.6505с, но было очень трудно искать пары, т.к. на DM=17 многие десятки записей

**Comment by vtyulb** [comment]
Замещено задачей #272
