### ISSUE TITLE
дополнительно к задаче 269

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#273]
помимо сложения динамических спектров и профилей по "insert", нужно еще и подсчитывать по этим же выделенным файлам среднее звездное время прихода транзиента. Т.е., считается среднее время прихода импульса в точках путем сложения всех импульсов и деления на количество импульсов. Если импульсов больше 3, то считается среднеквадратичное отклонение от среднего. Для всех этих сложенных импульсов на выходной рисунок или еще куда-нибудь выдается звездное время найденного RRAT до секунд и среднеквадратичное отклонение в секундах, а так же информация о том, сколько импульсов участвовало в сложении.

**Comment by vtyulb** [comment]
Сделано
