### ISSUE TITLE
баг в картинке выдачи индивидуальных импульсов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#274]
16 каналов верхних, отличается от 16 каналов нижних. В рисунке виден явный излом. Рисунок прилагаю.
![1919 21_signal](https://user-images.githubusercontent.com/11756008/27134566-a513a0e4-511e-11e7-867d-525b0a2463b1.jpg)

**Comment by vtyulb** [comment]
Программа всегда работает одинаково. Из-за разного усиления по каналам нижние раздвинулись чуть сильнее, верхние чуть слабее. При нормализации этот эффект исчезнет. Могу всегда раздвигать каналы на одинаковую величину, тогда какие-то будут серьезно наползать на другие, либо же все будет слишком плоское

**Comment by vtyulb** [comment]
Короче, надо посмотреть как будут выглядеть подобные импульсы в нормированном поиске. Потому что строгое расстояние между каналами даст просто другое искажение. Пока задачу закрываю
