### ISSUE TITLE
определение полуширины импульса

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#275]
Определение полуширины должно работать как по одиночному выбранному импульсу, так и по суммарному импульсу, собранному на одной DM(!!!). Если вдруг нечаянно отмечено несколько DM, то пусть считается полуширина по той DM, которая встречается чаще всего.

Полуширина определяется как ширина импульса на половине его высоты. Высота импульса считается от нулевого уровня. Для контроля лучше всего выводить в правом окне не ту странную штуку, которую ты выводишь сейчас, а импульс на который наложена линия нулевого уровня (так я увижу сразу правильный ли нулевой уровень в данном импульсе) и линия пересекающая импульс на середине высоты + в этом же окне должна быть выведена цифра этой самой полуширины в миллисекундах.

**Comment by vtyulb** [comment]
Сделано
