### ISSUE TITLE
Сложение среднего импульса

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#276]
Для очень многих импульсов, определяемых многократно, есть постоянная зависимость. Если импульс сильный, то он определяется много раз на всех мерах дисперсии, а если слабый, то может определится лишь на одной достаточно произвольной мере дисперсии. Например, транзиент 1609+1652 в блоке 109, модуле 2, луче 1 на мерах дисперсии 83 и 84 определяется по 5 раз, а если просмотреть все DM, на которых он виден, то есть 13 уникальных импульсов.
Задача: Если отмечены все DM, где виден транзиент, то при сложении всех импульсов нужно складывать лишь уникальные события. Т.е., нужно пропускать повторные события (сильный импульс должен складываться один раз). Это можно сделать и в ручном режиме, но уж больно муторно.

**Comment by vtyulb** [comment]
Сделано
