### ISSUE TITLE
получение среднего импульса и среднего динамического спектра

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#278]
Сейчас после получения готовой картинки и попытки нажатия (или изменения значения) меры дисперсии на экране появляется картинка, соответствующая одиночной записи.

Хотелось бы, чтобы после сложения динамических спектров можно было использовать возможность изменения DM с тем, чтобы было можно подгонять меру дисперсии (красную линию) к видимой на картинке полоске.

**Comment by vtyulb** [comment]
Сделано
