### ISSUE TITLE
баг определения периода

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#279]
Один из новых транзиентов оказался миллисекундным пульсаром. На четверном периоде он находится, а на двойном (т.е. на том на котором мы все время и ищем) не находится. 
Файл: 130815_18_N1 (длинные данные!!!)
Модуль: 3
Луч: 5
DM: 4-5
P=0.041515 - не ищет
Р=0.08303 ищет, гигантский сигнал шум + великолепный динамический спектр

**Comment by vtyulb** [comment]
> Забыл время пульсара: 13h26m42s

**Comment by vtyulb** [comment]
fixed
