### ISSUE TITLE
баг "pulsar analysis"

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#286]
не складываются средние профили (флешку с примером принесу)

**Comment by vtyulb** [comment]
Проверил, все складывается. Для требуемого эффекта требуется:
1) Загрузить все *.pulsar файлы
2) Выбрать первый файл из списка
3) Нажать на кнопку mem (profile)
4) Выбрать следующий файл
5) Нажать на кнопку M+ (profile)
6) Если еще остались файлы, то перейти на п.4

Теперь если навести мышкой на блок profile, то будет светиться этот мини-хелп
