### ISSUE TITLE
пульсары на больших DM

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#287]
Посмотрел усредненные спектры мощности по "длинным" данным и с изумлением обнаружил PSR1922+2110 (период 1.078, DM=238), лучом ниже нашего могучего 1921+2145 (модуль 6, луч7). Остается вопрос - есть ли у него сильные импульсы, чтобы увидеть его как транзиент. Картинку прикрепляю
![psr1922 2110_dm238](https://user-images.githubusercontent.com/11756008/28203578-07154bfa-6883-11e7-8bc6-f17c4f995f42.jpg)
других сильных пульсаров по длинным данным не обнаружено

**Comment by vtyulb** [comment]
Проверил все, никаких видимых импульсов не нашел за 2 самых сильных дня
