### ISSUE TITLE
сжатие данных

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#29]
Обнаружил, что по несколько часов трачу на то, чтобы загрузить несколько суток обработки в режиме "low memory". Хорошо бы, чтобы для каждых, обработанных целиком суток, был одиночный файл, который содержит целиком каталог за сутки и рисунки двойного периода. Тогда можно было  бы быстро подгружать этот файл или файлы (если суток несколько) и это бы очень сильно облегчило жизнь.

**Comment by vtyulb** [comment]
Сделаю сегодня
