### ISSUE TITLE
frb фильтр

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#295]
Если посмотреть на меры дисперсии, то можно увидеть, что
1) Подавляющая часть источников в каталоге имеет одну и ту же меру дисперсии
2) В каталог выводится лишь одна мера дисперсии, тогда как очень часто есть несколько равнозначных мер дисперсии в записи
Предлагаю:
1) Вносить в каталог все меры дисперсии у которых SNR больше заданного значения
2) Сделать фильтр "одинаковые дисперсии". Если в каталоге 3 и больше одинаковых мер дисперсии в разных модулях и лучах, то не показывать эти кросскорелляции

**Comment by vtyulb** [comment]
Фильтр вполне эффективно заменяется стандартным фильтром транзиентов "Multiple rays filter". Вносить все меры дисперсии в каталог я смысла не вижу, т.к. это даст эффект только для пульсаров, а в большей части просто раздует помеховые записи.
