### ISSUE TITLE
Разрисовка красной линии в DM

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#296]
Ниже "Dispersion" "show" сделать
         "Shift"      +    пустой квадратик для вписания числа
Если в "Shift" стоит галочка, то квадратик становится активным. В него можно занести положительное или отрицательное число. Когда программа запущена, то по умолчанию выставляется красная линия слева на расстоянии несколько пикселов от линии транзиента. Если  "Shift" запущена, то значение "0"
стоит по умолчанию, если внесено положительное число, то красная линия сдвигается влево на число пикселов в окошке, если внесено отрицательное число, то сдвигаем линию вправо. Заданное значение сдвига работает до тех пор пока программа не закрыта. Т.е. не должно быть сдвига на "0" если я начал смотреть новый блок

**Comment by vtyulb** [comment]
Сделано
