### ISSUE TITLE
переменность источников

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#305]
Прежде, чем дальше продвигаться нужно сделать какую-то минимальную фильтрацию. Я просмотрел по калибровочному источнику, сидящему в модуле 1 большие выбросы вверх и вниз и обнаружил.
1) Регулярные выбросы вверх - это попадания источника на ступеньку.
2) Выброс вниз - нет источника в записи.
3) Большой выброс вверх. На источнике сидит очень сильная помеха
4) Маленький выброс вверх. Чаще всего связан с ионосферными мерцаниями, которые сильно искажают источник.
Предлагаю: Пройтись по конечной записи 5 точечным медианным фильтром и посмотреть что получится. Если чистка будет нормальной буду думать, что делать с исследуемым источником.

**Comment by vtyulb** [comment]
Сделано, при разнице в пять раз по сравнению с соседями точка вырезается. Повтор идет 2 раза
