### ISSUE TITLE
не считаются некоторые дни

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#313]
Слава, привет!
Марина считала один из пульсаров на внешнем сервере (см. сайт со списком выполняемых задач). Два дня вышли через "превышение времени счета", причем было сделано по 2 попытки на каждый день. Когда Марина переписала эти файлы на свой компьютер, то оба дня спокойно посчитались.

Задание не слишком срочное, но если будет посмотри

**Comment by vtyulb** [comment]
Проблема была в отсутствии файлов. Теперь если файлов нет, то программа останавливается сразу
