### ISSUE TITLE
сохранение рисунков

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#315]
Сегодня для статьи пытался сохранить рисунки svg формате. Оказалось, что при использовании Save Image в меню сохраняется лишь верхняя часть рисунка (профиль). Для png та же история. Т.е. рисунки друг под другом (профиль + динамический спектр) я сохранить не могу.

**Comment by vtyulb** [comment]
Договорились, что сохранение полных рисунков завязано на кнопки в левой части Analytics
