### ISSUE TITLE
Плотность потока в единицах температуры

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#318]
Часть вещей нужно перепроверить, а часть запрограммировать
1) Должно быть: чтение координат источника, пересчет на год наблюдений, определение вершины источника, отступ от вершины на договоренное количество секунд (скорее всего договаривались +- 30сек от вершины), усреднение всех точек внутри этой минуты (+ независимо во всех частотных каналах, + независимо и по длинным данным), отступление от вершины на половину длинны источника, которая задается с использованием склонения источника, далее от полученной координаты "нуля" отступ в каждую сторону на +-30сек, усреднение, затем вычитание из высоты источника на вершине высоты источника в нуле, запоминание этого числа в единицах АЦП. Вообще говоря очень полезно перед всеми этими процедурами пройтись по источнику трехточечным медианным фильтром с расстоянием между точками 1.5сек.
2) Должно быть: файл с оценками высоты ступеньки в единицах АЦП, оценка ожидаемой высоты ступеньки в месте расположения вершины источника.
3) Должно быть: Высота ступеньки делится на высоту источника, запоминается это значение, дата.
4) Нужно доделать: в выходном файле должны быть все даты, в том числе и те, когда оценка не делалась или была некорректной. Для всех "некорректных" данных в месте оценки высоты источника должно стоять "no".  Таким образом можно будет легко сравнивать наблюдения разных источников за одни и те же даты, удалять дополнительно (синхронно) данные для двух и более источников при использовании EXEL, делать разного рода сортировки, составлять рисунки за одни и те же даты. 
5) Проверку работоспособности программы в автоматическом режиме, можно сделать по источнику 4С+39.23: 
B1950 8h21m36s; 39o27'48"
J2000  8h24m55.5s; 39o16'42"
Источник находится модуль 1, луч 8.
Картинку того, как он выглядит сейчас прикрепляю (черные точки и ежегодные выбросы)
![variability_test_for_polina](https://user-images.githubusercontent.com/11756008/35496499-22542c74-04d7-11e8-9455-5f42e66e9162.jpg)
6) Если будет возможность прошу не затягивать, так как там вырисовывается статья по межзвездным мерцаниям активных ядер галактик, а Полине стартовать обработку бессмысленно, пока программа не будет доделана в нужном виде.

**Comment by vtyulb** [comment]
Сделано без сброса всех дат, т.к. зачастую непонятно к какому часу относится источник (то что будет считаться ручками автоматом разойдется с программой). Проблему соответствия дат надо решать на уровне exel сортировками и соответствием.

Если что-то по плотности потока не работает, то открой новую задачу
