### ISSUE TITLE
возможное решение для сложения всех гармоник в автоматическом режиме

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#323]
Если в длинных данных (в спектрах) мы обнулим дорожку вначале, где лезет низкочастотный шум, затем обнулим все известные помехи, то у нас останется чистая шумовая дорожка. Если провести процедуру автокорреляции, то на сдвигах, соответствующих периоду пульсара должны вылезти дополнительные пики. В первом пике сигнал к шуму должен быть максимальным, так как там будут сложены все гармоники!!!

**Comment by vtyulb** [comment]
Задача перенесена в #322
