### ISSUE TITLE
парковка синей стрелки (для удобства работы с рисунками)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#327]
По умолчанию первая синяя стрелка выставляется на первую с конца найденную гармонику. Но когда готовишь рисунки к статье синие стрелки могут мешать и приходится тратить лишнее время на их стирание. Предлагаю сделать так, чтобы при любых просмотрах фурье спектров при заходе на новый луч первая синяя стрелка **всегда** становилась на последнюю точку массива, а потом уже движение стрелок как оно идет и сейчас.

**Comment by vtyulb** [comment]
Сделано
