### ISSUE TITLE
работа whitezone (транзиенты)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#328]
Слава, мы уже говорили о белой зоне в случае включения фильтров. Сами фильтры работают более менее адекватно, но если они включены, то белая зона строится некорректно. Можно ли ее исправить? Корректное перестроение белой зоны позволит видеть накопленные слабые транзиенты, токда как помехи уйдут.

**Comment by vtyulb** [comment]
Сделано. Я сам был удивлен такому поведению, но генерация белой зоны действительно предполагалась один раз только при загрузке данных и без подключения фильтров
