### ISSUE TITLE
динамические спектры (транзиенты)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#329]
Мы уже испытывали динамические спектры на больших DM. Смотрятся они ужасающе и пользоваться ими затруднительно. В то же время на DM=100 дин.сп. все еще приемлемый для просмотра на экране. Предлагаю сделать следующее:
На DM=100-200 усреднить все точки дин.сп. по времени попарно, тогда картинка, соответсвтующая DM=200 по длине будет равна старой картинке с DM=100, а новая картинка с DM=100, будет соответствовать старой картинке с DM=50.
На DM=200-300 усреднить все точки по 3 штуки...
На DM=900-1000 усреднить по 10 точек, т.е. по 125 мс (это не страшно, так как размытие импульса из-за меры дисперсии в соседних каналах все равно будет порядка 400 мс. При этом DM=900 будет по длине как DM=90; а DM=1000, как DM=100.
Там еще, конечно, будет заморочка с корректным проведением красной линии, которая показывает найденную меру дисперсии, но мне кажется это не очень страшно.
Я предлагаю не трогать посчитанные файлы, а делать это усреднение при загрузке блока, если выставлен какой-нибудь дополнительный флажок типа "Large DM show"

**Comment by vtyulb** [comment]
Сделал автоматическое принудительное усреднение при дисперсиях > 200
