### ISSUE TITLE
поиск транзиентов (проверять, обсуждать...)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#334]
Слава, у меня есть чувство, что при поиске транзиентов веса точек, лежащих на линии равны. Т.е., если по какой-то причине один из пикселей физически будет иметь очень большое значение, а еще сколько-нибудь штук будут иметь значения выше среднего, то геометрический фильтр сработает, сигнал к шуму определится на приличном уровне, а вот в динамическом спектре будет пусто. Т.к. на больших мерах дисперсии длина линии вдоль которой происходит суммирование пикселей большая, то вероятность зацепить такой "мощный пиксель" пропорциональна длине линии динамического спектра. Чем большие меры дисперсии мы будем обрабатывать, тем больше будет ложных срабатываний. Как работать с этим нужно обсудить...

**Comment by vtyulb** [comment]
Нет, это не совсем так.
1) Да, если один из пикселов будет иметь большой вес, то возникнет объект. В режиме поиска транзиентов проверяется только что нет "вертикальных полос", которые будет иметь вес хотя бы 70% от текущего. В этом режиме были сделан поиск транзиентов по длинным данным.
В режиме FRB более хороший критерий - там просто выбрасываются 2 верхних и 2 нижних значения на умножаемой дисперсии. Поэтому там меньший вес имеют выпавшие в какую-то сторону пикселы.
2) Да, геометрический фильтр срабатывает, если есть ряд удачных пикселов. Оно так есть, в этом вся его суть. Но от дисперсии это не зависит - потому что проверяться будут всего 32 пиксела.

Вообще, я бы не надеялся на геометрический фильтр, он легко может срезать какой-нибудь объект. Когда объектов сотни, это не важно. Но когда объект один, это может оказать 50/50, что будет сильно обидно. А если у видимых FRB будут какие-то особенности на нашем телескопе, то вероятность может совсем испортиться. Так что лучше вообще без фильтров.

В случае обычного же поиска транзиентов, я могу предложить только выкидывание из суммироемой прямой 2 максимальные точки. Но это стоит делать только после прогона на текущем алгоритме дисперсий 100-200, чтобы ничего не испортить.
