### ISSUE TITLE
а была ли новая сборка???

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#34]
Слава, сделал ли ты мне новую сборку. Я проверял триплеты и у меня ничего не изменилось
Посмотри, пожалуйста, пример не работающей иттерации. Ставил поиск трех дупликатов и произвольное (до 4) число иттераций. Модуль 4, луч 5. Время порядка 18:56:00.
Файл период SNR
280215_10 8.6719 4.8
151214_15 8.9474 5.2
311214_14 8.7849 5.0

Вычисляем расплывание импульса по формуле, которую я тебе давал (разница в периодах умноженная на количество периодов на 180 секунд):
(8.9474-8.6719)*20=5.5секунд.

**Comment by vtyulb** [comment]
Да, забыл сборку сделать. Выложил сборку
