### ISSUE TITLE
нет рисунка в исходных обработанных данных

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#35]
Слава, привет! Опять нашелся случай, когда нет рисунка, соответствующему файлу. Я загнал 10 обрезанных от дорожки файлов в программу. Выставил режим: мод=1; луч=1; фильтры multiple и strange отжаты. 5 дупликатов, 3 иттерации. Double periods - отжата. Определился в том числе объект за 311214_21; Р=9.9380; SNR=4.9; DM=6. На рисунке пусто - не нарисовано ни одной точки. Его же нет и в оригинальных обработанных данных с дорожкой (проверил seacher). На правой оси стоят буквы "nan"

**Comment by vtyulb** [comment]
Частично исправил: данные побиты, но даже в побитых дорожках процентов 90% корректно. График будет рисоваться, но не полностью
