### ISSUE TITLE
Падение при подгрузке длинных данных

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#350]
Проявляется только на конкретной машине.
При удалении fork() и releaseData() в генерации белой зоны поведение меняется, подгрузка происходит, на все падает при показе серой зоны.

Нужно перекинуть сборку x64 qt на битую машину и что-то сделать с дебагом. 

Есть доступ через teamviewer

**Comment by vtyulb** [comment]
Исправлено, больше падений не должно быть.

Было чтение освобожденной памяти, в линуксе все успевало прочитаться (речь идет о десятках наносекунд после освобождения). Винда успевала освободить память и роняла программу с access violation.
