### ISSUE TITLE
причина некорректного сложения спектров мощности

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#359]
При сложении спектров мощности в режиме "normalization" в последнем релизе пропало почти четверть всех модулей и лучей. Я перепроверял отдельные лучи и обнаружил, что если в каком-то луче появляется пустой экран в белой зоне, то в серой зоне первым файлом идет спектр у которого в колонке SNR стоит число -555. Сам индивидуальный спектр тоже не виден. Оцифровка оси OY показывает числа со степенью +29.

**Comment by vtyulb** [comment]
Похоже на правду, тоже на него наткнулся. Пофикшено
