### ISSUE TITLE
сломался точный поиск

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#43]
Слава, точный поиск перестал организовывать директорию с результатами поиска. Запуск я делаю, как и обычно, от имени администратора. На экране все то же происходит как обычно. T.e. видно, что программа перебирает последовательно все меры дисперсии, но результаты не сохранятся на жестком диске.

**Comment by vtyulb** [comment]
Оказывается NTFS не позволяет создавать файлы с символом ':'
