### ISSUE TITLE
некорректное время по началу счета в режиме "precise..."

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#45]
Слава, случайно обнаружил, что в режиме "precise..." время, которое задается как середина отрезка на котором надо найти пульсар является временем, от которого отступается 90сек и затем ищется пульсар. Т.е. он ищется не в оптимальном месте. Нужно, чтобы от центрального задаваемого времени отступалось 45 секунд (это будет временем старта), а далее выполнялись все соответствующие процедуры.

**Comment by vtyulb** [comment]
Отступается сейчас (как и раньше) +- 2 минуты
