### ISSUE TITLE
новый фильтр к поиску дупликатов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#47]
Нужен еще один фильтр в "custom filters". Нужна проверка совпадения периода кандидата в пульсары между лучами. Если "пульсар" виден в трех и более разных лучах одного модуля, то в таблицу дупликатов его не выводить. По умолчанию этот фильтр должен быть нажат...

**Comment by vtyulb** [comment]
Too hard to implement
