### ISSUE TITLE
задача по поиску гигантских импульсов (дополнение)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#52]
В чем проблема!!!
Если вдруг данные засорены помехами, то на каждый помеховый пик программа сейчас реагирует как на найденный гигантский импульс. Нужно уметь выкидывать ненужные пики и выдывать на экран информацию лишь по реальным пикам. Вопрос выкидывания решается учетом того, что реальные импульсы пульсара имеют меру дисперсии, которую мы собственными руками вводим при поиске гиг.импульсов у данного пульсара. Возможных решений два. Выбери то, которое удобнее реализовать. Если придумаешь свое решение, то нужно будет его обсудить.

Решение один:
Берем откалиброванные по ступенькам по всем частотам данные. Складываем без учета меры дисперсии (первый массив) и с учетом меры дисперсии (второй массив) все частотные каналы. Если пиковый сигнал принадлежит пульсару, то в данных после учета меры дисперсии он будет больше по абсолютной величине, чем сигнал в котором напрямую сложились все точки. Именно такие сигналы (т.е. номера точек, где они находятся) и динамические спектры этих пиков и надо выдавать на экране.

Решение два:
Мера дисперсии пульсара известна и программа считает задержку прихода сигнала по времении по всем частотным каналам. Находим вершину на частоте первого канала, по задержке считаем куда сигнал должен был попасть на последнем частотном канале и смотрим где реально сидят максимумы в каналах (расстояние между локальными максимумами должно быть близко, с точностью до плюс минус одной точки, к посчитанной задержке сигнала). Этот способ может оказаться неустойчивым в работе, т.к. длительность импульса может быть больше, чем постоянная времени и потребует дополнительных усилий при проверке.

**Comment by vtyulb** [comment]
Если внутри большого импульса в каком-то канале нашелся импульс в 10 раз превышающий среднее значение, то большой импульс считается помехой.
