### ISSUE TITLE
поиск гигантских импульсов (дополнение) 

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#57]
Программа поиска гигантских импульсов работает вроде бы корректно (нужно будет провести большие тестовые работы), но как выяснилось нужен еще один шаг. После вывода на динамическом спектре найденного гигантского импульса, необходимо иметь возможность нажать на кнопочку "continue" и тогда выводится следующий найденный гиг. импульс, либо на кнопочку "stop" и тогда программа поиска гиг. импульсов прерывается, но программа "bsa-analytics" не останавливается. Тогда можно будет попробовать в этом или другом файле поискать гиг.импульсы у других пульсаров не перезапуская программу.

**Comment by vtyulb** [comment]
done
