### ISSUE TITLE
изменение дизайна:

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#58]
В меню пульсар есть три блока, которые путаются у потребителей. 
1) Первый блок - это поиск пульсаров, который под виндой не работает.
2) Второй блок - это анализ файлов, сделанных поисковой программой. Состоит из двух частей. Анализ данных и показ шумовой дорожки и анализ данных с выкидыванием шумовой дорожки и показа лишь двойного профиля пульсара.
3) Третий блок - разные процедуры с пульсаром и не только с ним.
Предлагаю:
1) Первый и второй блок выделить в отдельное направление и назвать Pulsar Search. В нем оставить первые три строки из старого меню: Pulsar searcher, Pulsar analytics, Pulsar analytics low memory
2) Третий блок разбить на два принципиальных куска. Один кусок связан только с пульсарами. Для этого куска в главное меню поставить новое окно и назвать Investigation of Pulsars. 
       Если посмотреть на процедуры, которые мы делаем для извлечения параметров пульсара: точный поиск, оценка энергии, поиск гиг. импульсов и другие, то выясниться, что в большинстве случаев приходится вносить одни и те же параметры. Номер модуля, луча, период пульсара, меру дисперсии и прочее. То есть если я хочу для одного известного пульсара получить полную информацию, то я раз за разом буду вносить одни и те же параметры. 
        Предлагаю, что бы при входе в меню "Investigation of Pulsars" разворачивалось большое подменю с кучей соприкасающихся колонок. Наверху этого подменю должны стоять надписи "Presice Search", "Presice Timing" и прочие. Рядом с каждой надписью окошко для галочки. Если я, например, отмечу галочкой все пункты, то программа должна посчитать все, включая поиск гигантских импульсов для данного пульсара. Когда я, например, выбираю модуль и луч, в которых проводятся процедуры, то во всех колонках должно автоматически выставляться одинаковое значение модуля и луча. Обрати внимание, что сейчас есть очень опасное наложение нескольких процедур в этой части программы. Например, в "flow detetcor" вмонтирован поиск гигантских импульсов, который является отдельной процедурой. В общем нужно пересмотреть весь этот набор подпрограмм таким образом, чтобы они не путались друг с другом. Кстати процедура оценки Фарадеевского вращения для пульсаров должна остаться. Там методология немного другая в сравнении с использованной, но смысл будет ровно тот же.

Второй кусок (обработка не связанная с пульсарами), выделить в отдельное направление и в главном меню ввести новое окно, которое назвать "Others". В это меню перенести озвучку файлов и фарадеевское вращение, которое сделано для источников.

**Comment by vtyulb** [comment]
В каком-то виде сделано. То что не сделано, вроде бы, больше неактуально.
