### ISSUE TITLE
Первый шаг при работе с известными пульсарами (выравнивание каналов)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#59]
Оценка плотности потока пульсара (новые детали):
На настоящий момент времени высота среднего профиля пульсара сравнивается с высотой ступеньки. Высота ступеньки предполагается 2100 или 2400 градусов Кельвина (не помню точно). Мы измеряем эти высоты в единицах АЦП после сложения всех частотных каналов и всех импульсов, а затем из пропорции оцениваем высоту среднего профиля пульсара в Кельвинах. На самом деле эта процедура должна быть более сложной.
Пусть: 
n1=(Высота_максимума_ступеньки_в_АЦП/высота_минимума_ступеньки_в_АЦП) - первый канал
Тсистемы_в_Кельвинах_1канал=Tсис_1
Тгенератора_шума_в_максимуме_ступеньки_в_Кельвинах=Тмакс
Тгенератора_шума_в_минимуме_ступеньки_в_Кельвинах=Тэкв
Tсис_1=(Тмакс -  n1*Тэкв)/(n1-1) и такая же процедура для всех частотных каналов.
Далее:
Тмакс=2400 Кельвин (эту температуру с высокой точностью дает генератор шума)
Тэкв=температуре окружающей среды(меняется со временем года) = 280К (приблизительно)

В результате этой работы мы получим 6 или 32 значения T_сис. Фактически они показывают коэффициенты усиления в каналах. Необходимо найти такие множители к каждому каналу, чтобы усиление стало одинаковым. Т.е. Тсис_новое=k1_Tсис_1=k2_Tсис_2=k3*Tсис_3 и так далее. После умножения всех исходных чисел внутри обрабатываемого отрезка на соответствующие коэффициенты k1,k2,k3 и прочие можно приступать к процедурам обработки.

В частности при оценке плотности потока пульсара мы фактически оцениваем его высоту минус нулевой уровень. Получившееся значение сравниваем с высотой ступеньки, полученной после выравнивания во всех каналах.

Эти же процедуры выравнивания каналов будут обязательны для оценки высоты гигантских импульсов, оценки фарадеевского вращения пульсара. Они же будут обязательными для оценки фарадеевского вращения обычных источников и так далее.

**Comment by vtyulb** [comment]
Закрыто из-за #95
