### ISSUE TITLE
новая программа поиска (блок схема)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#60]
Судя по всему, прежде, чем делать базу данных, нужно оценить работу новой методики поиска. Программу поиска нужно сделать независимой, но выходные файлы должны восприниматься программой BSA_analytics.

Здесь я перечисляю кратко крупные основные блоки и эту задачу можно будет закрыть как только будут сделаны все эти блоки, прописанные в отдельных задачах.
1) Чтение данных (из старой программы)
2) Переформирование данных
3) Работа с шумовой дорожкой (дополнительные выходные файлы)
4) Чистка помех (из старой программы)
5) новый алгоритм поиска, предварительный анализ существования пульсара
6) сокращенная запись выходных файлов (лишь вид с двойным периодом) Был в старом поиске?

**Comment by vtyulb** [comment]
Задача не актуальна (https://github.com/vtyulb/BSA-Analytics/issues/89)
