### ISSUE TITLE
Переформирование данных (переформирование лучей)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#61]
В отдельном письме за 31.12.2015 высылаю программу из которой нужно сделать модуль к твоей программе. Входные параметры к программе: частота в мегагерцах и номер кабеля. Первые 32 кабеля на БСА не задействованы, поэтому 1ый модуль и 1ый луч соответствуют кабелю 33. 6ой модуль и 8ой луч соответствуют кабелю 128.

Суть дела в том, что мы имеем многочастотные данные. На каждой частоте БСА имеет для каждого луча свое направление на небе по склонению. В тех лучах, которые мы обрабатывали раньше - эта зависимость между частотой и направлением была не очень сильной. На нижних склонениях зависимость сильная.

В силу этого будем делать универсальную программу, которой все равно с какими лучами работать. 
1) Считываем все значения частот из обрабатываемого файла из паспорта. Для шестичастотных наблюдений эти частоты от 109.20...МГц до 111.28... МГц. Подставляя формально эти 6 частот (или 32 частоты для "длинных" данных), получаем матрицу в которой будет 6 (или 32 столбца) и 96 строк (для 96 лучей). В пересечении строк и столбцов будет находится склонение (градусы и и десятичные доли градуса), на которое направлен луч на данной частоте наблюдений. (Соответственно не забыть, что ступеньки обрабатываются из "правильных" лучей)
2) С использованием этой матрицы подбираем такие 6 (или 32) значений направлений из базового и соседних кабелей, чтобы эти направления отличались не более, чем на половину расстояния между лучами (см. тест 3).
3) Первый тест программы: Возьмем 5 модуль каналы 3, 4 и 5 (соотвественно, это кабели 115,116 и 117). Частоты наблюдений 109.21; 109.62; 110.04; 110.45; 110.87; 111.29 МГц
Посчитанные значения направлений будут:
115 кабель: +1.08; 1.24; 1.42; 1.58; 1.74; 1.90
116 кабель: +0.38; 0.55; 0.72; 0.89; 1.06; 1.22
117 кабель: -0.33; -0.15; +0.02; 0.19; 0.37; 0.54
Расстояние между значениями направлений в одной колонке примерно 0.7 градуса. Мы считаем, что смотрим в одно место, если направления разошлись не больше, чем на половину угловой меры между направлениями. Т.е. 0.7 делить на 2 = 0.35 градуса. Берем базовое направление +0.38 градуса (116 кабель). Новый сформированный луч должен содержать направления отличающиеся не более, чем на половину от выбранного базового направления (т.е., от +0.03 до +0.73 градуса) Тогда при обработке формируются следующие 6 направлений: с кабеля 116 берем +0.38; +0.55; +0.72; с кабеля 117 берем +0.19; +0.37; +0.54 с которыми и проделываем процедуры по поиску пульсаров.
4) Второй тест программы. Берем известный сильный пульсар в нижней площадке и проверяем изменилось ли отношение сигнала к шуму до и после процедуры переформирования каналов с учетом направления. SNR должно улучшится примерно в 2 раза по сравнению с тем, как если бы мы тупо взяли все частоты одного луча.

**Comment by vtyulb** [comment]
Задача не актуальна (https://github.com/vtyulb/BSA-Analytics/issues/89)
