### ISSUE TITLE
Программа поиска гигантских импульсов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#65]
1) Программа не работает с "длинными" данными под виндами 
2) табличка с номером точки, где находится гиг.импульс ложится поверх спектра (приходится все время ее сдвигать). Сделать, чтобы она была сбоку от спектра.
3) на табличке с номером гиг.импульса давать дополнительную информацию: а) сигма шумов на периоде пульсара; б) плотность потока, определенная по ступеньке.. Эта информация позволит сразу оценивать мощность импульса.

**Comment by vtyulb** [comment]
Из задачи #67
> Забыл написать. На выводе помимо номера точки максимума импульса, сигмы шумов, плотности потока источника нужно также выводить значение высоты импульса (т.е. значение = значение в максимуме - значение в минимуме (а лучше минус значение в средней точке))

**Comment by vtyulb** [comment]
Сделано
