### ISSUE TITLE
разрисовка данных (нормировка в выдаваемом окне)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#66]
напоминаю, что просмотр данных в частотных каналах оказался неудобным. Все-таки лучше устроить нормировку по значениям самих точек в частотном канале внутри окна. Что-нибудь вроде размер окна равен учетверенному (максимальное значение на данном частотном канале минус минимальное значение). Тогда будет видна и толщина дорожки и в то же время она не будет забивать весь экран. Если вдруг на частотном канале будет не убираемая помеха, то и черт с ней.

**Comment by vtyulb** [comment]
done
