### ISSUE TITLE
изменения дизайна программы (задача 58) дополнение

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#68]
Как уже писал в задаче 58 в настоящий момент есть неудобные места в меню программы, которые нужно исправить.
1) Нужно ввести новый элемент в верхнее меню (см. прикрепленный рисунок). После "Investigation of pulsar" добавить новое окно меню "non pulsar investigation". На данный момент в этом меню будет только один элемент "rotation measure", который нужно перенести из меню "Investigation of pulsar"
2) В меню "Investigation of pulsar" ввести новый элемент "Search for impuls". Сейчас он находится в "Flow detector", что не правильно. При вызове "Search for impuls" в диалоговом окне появится все то же, что и для "Flow detector". Вероятнее всего из "Flow detector" уйдет параметр sensitivity и number of points (обсудить со мной, т.к. я сейчас не помню, что эти элементы могут делать в "Flow detector"
3) Записывать на текущий сеанс работы программы файлик, который обновляется каждый раз при обработке нового пульсара, который уничтожается при закрытии программы и в котором хранится текущая информация общая для любых исследований пульсаров (mod, ray, disp, period, time). Если, например, после presice search, я захочу выбрать flow detector, то из этого файлика нужно автоматически переписать всю возможную информацию в соотвествующие строки.
4) При вызове меню Presice Search в диалоговом окне на самом верху появляется надпись  Presice Search, при вызове всех остальных пунктов меню в диалоговом окне наверху появляется надпись "Dialog,,,". Хотелось бы, чтобы там по аналогии с Presice Search появлялись соответствующие записи.

![fig2](https://cloud.githubusercontent.com/assets/11756008/12324866/f057fdbe-bad6-11e5-857d-635f3a8c007e.jpg)

**Comment by vtyulb** [comment]
После сегодняшних изменений интерфейса точно не актуально
