### ISSUE TITLE
сложение файлов

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#69]
1) Предусмотреть возможность сложения файлов, которые находятся на разных выносных дисках. Например я перечисляю нужные года, затем отключаю устройство, подключаю новый диск, затем говорю "Складывай данные", затем когда программа сложит все данные с этого диска, то она должна сказать, что данных не хватает и попросить другой диск.
2) До какого-то момента в паспорте не писалось UTC время. Для всех этих данных разница между московским временем и UTC равна 4 часа. Нужно проверять время и если нет UTC вносить эту поправку. Этот кусок должен работать как в программе просмотра, так и при складывании файлов.

**Comment by vtyulb** [comment]
done
