### ISSUE TITLE
поиск пульсаров со сглаживанием

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#70]
Для коротких данных:
1) Поиск производить с шагом меры дисперсии 15.
2) Для сложенного файла предусмотреть несколько разных вариантов обработки:
а) просто по сложенным данным
б) пройтись по суточному файлу скользящим средним с шагом 3 точки. При оценке SNR увеличивать его на корень из 3.
в) то же, что и б), но с шагом 5 точек. SNR увеличивать на корень из 5.
3) Поиск делать по 4 минутам.
4) Если в каком либо луче найден пульсар с SNR=4 и более, то нужно провести сложение с соседним лучом с тем пульсаром, который найден параллельно. Полученные точки разделить на корень из 2. Посмотреть получившееся SNR и если оно меньше 5, то проигнорировать новый источник и не вносить его в каталог, если его SNR меньше, чем SNR любого луча, то запись не производить. Если получилось значение больше 5, то в каталоге должна быть соответствующая отметка. Например, пульсар обнаружен в модуле 1 луче 8 и в модуле 2 луче 1. Его SNR больше, чем отдельные SNR в лучах 8 и 1. В каталог вносится метка 
модуль      луч
1+2           8+1
Я надеюсь, что этот способ улучшить координату по склонению и поможет найти пульсары, которые находятся на грани обнаружения.
При таком сложении лучей нужно иметь точное время первой точки в обоих складываемых каналах и оно должно совпадать!!! Сейчас ты считаешь его достаточно произвольно и делаешь кольцевой сдвиг в массивах, чтобы на экране данные смотрелись красиво.

**Comment by vtyulb** [comment]
Сделано, опция --flowing-window
