### ISSUE TITLE
сложение файлов 

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#71]
При использованном алгоритме после сложения 3 лет в сложенной записи исчезли все пульсары, включая сильные. Все-таки перед процедурой сложения нужно проделать предварительную работу в ходе которой создать файлы таблицы в которых должна быть информация о том, какие звездные минуты в какие дни были слишком зашумлены и в эти зашумленные дни должны быть обнулены и не использоваться при дальнейших сложениях. Для этого:
1) Проходимся медианным фильтром по записи (избавляемся лишь от импульсных помех)
2) Делаем оценку дисперсии шумов (сигмы шумов) для каждой звездной минуты каждого луча БСА3 за все дни и годы. Получаем таблицы, которые в конечном счете руками разместим в папке, где находится программа поиска пульсаров.
3) Берем первую звездную минуту первого луча седьмого канала и ищем медианное значение сигмы шумов в данном луче за все годы. Запоминаем это значение. Затем берем вторую и т.д. до 60ой минуты. Берем первую звездную минуту второго луча..... и т.д. В результате получим таблицу медианных значений шумов. В этой таблице будет по горизонтали 60 значений медианных значений сигмы шумов (звездное время) и по вертикали 48 строк (по количеству лучей).
4) Сопоставляем значения из таблицы полученной в (3) с таблицами полученными в (2). Сравниваем значение сигмы шумов (3) данной минуты со значением этой минуты этого луча за конкретный день. Если это значение сигмы шумов из (2) в два и более раза превышает медианное значение из (3), то данную звездную минуту в данный день нужно обнулить целиком. Соответственно во вновь образованной таблице появится метка какие звездные минуты и в какие дни нужно обнулить.
5) У нас после (4) появилась таблица, которая говорит о том в какие даты первую, вторую,....,, шестидесятую минуту можно сложить за все складываемые годы. 
6) Так как каждая минута может быть сложена разное количество раз (из-за присутствия или отсутствия мерцающих источников, сильных солнечных бурь, гроз и т.д.), то каждый луч может получиться "рваным". Там где мы делали много сложений, дорожка будет узкая (максимальное отношение сигнала к шуму), а там где сложений мало, дорожка получится широкая (минимальное отношение сигнала к шуму). Поэтому в сложенном канале нужно ввести весовые коэффициенты. Это делается следующим образом. Ищется число, показывающее сколько было  сложений по максимуму в данном луче. Запоминается это значение. Затем проверяется сколько было сложений в первой минуте. Все значения точек первой минуты делятся на корень (максимальное_значения_сложений/количество_сложений_в_данной_звездной_минуте). То же самое со второй минутой и т.д.. Затем все то же самое со вторым лучом.
7) Когда вычитать нулевой уровень пока не знаю. Если вычитаем с самого начала, то недовычищенные помехи могут очень сильно испортить конечную (суммированную) запись. Если вычитаем после обнуления плохих кусков, то вычитания нулевого уровня нужно проводить в каждой звездной минуте не зависимо и (как мне думается) можно это сделать уже после сложения всех файлов. В принципе это можно сделать прямо вычитанием прямой из всей звездной минуты.

**Comment by vtyulb** [comment]
done
