### ISSUE TITLE
сложение файлов (короткие данные)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#72]
Длина солнечных суток в секундах 24*3600=86400
Длина часа в секундах=3600
Постоянная времени=0.0999424с (нужно читать из паспорта). Длина часа в точках=3600/пост.вр.=
36020.748 точки. Понятно, что дробные точки записать нельзя, поэтому хвост каждого часового файла обрезается. Я просмотрел кучу реальных файлов и увидел, что в часовом файле записывается от 36017 до 36020 точек. Т.е. часовой файл в действительности еще короче, чем он должен быть от 4.7 точки до 0.7 точки. Следовательно, во время сложения в конец файла нужно добавлять не значащие точки (например со значением равным последней точке в данном модуле и луче). За солнечные сутки при плохом раскладе может быть потеряно 4.7*24=112.8 точки=11.3 солнечной секунды. Может быть 2 разных принципиальных подхода к сложению файлов.
1) Реализуется в урезанном виде тобой. Считаем звездное время первой точки, затем второй и так далее пока не набираются полные звездные сутки. Счет времени начинается всегда от UTC времени, которое дано в паспорте наблюдений часового файла. В этом подходе отсутствующие точки в конце каждого часового файла просто игнорируются. Т.е. мы получим звездные сутки с некоторыми пропусками в конце каждого часового файла. Затем, когда внутри 24го часа звездные сутки заканчиваются и начинаются вторые звездные сутки, мы первую точку вторых звездных суток складываем со значением первой точки  первых звездных суток и продолжаем наш счет. Технически этот подход самый правильный. Особенно с учетом того, что в длинных данных постоянная времени еще в 10 раз меньше, чем в коротких данных. Есть лишь две неприятности. Первая: Звездные секунды и солнечные секунды не совпадают по длительности. Поэтому должны складываться точки из разных звездных суток если разница во времени меньше, чем половина точки. Т.е. этот момент нужно четко контролировать. Вторая: Тратится время на подсчет звездного времени каждой точки (кстати считать нужно время лишь 7го канала, оставшиеся 6 частотных каналов имеют то же самое время!!!). А это примерно 860000 подсчитанных звездных времен за час и умножить на 24 за сутки. ПУСТЬ ВСЕ СКЛАДЫВАЕТСЯ МЕДЛЕННО, ЗАТО ПРАВИЛЬНО!!!
Из тонкостей нужно отметить лишь то, что нужно иметь в памяти некий шаблон звездных суток с "идеальным" посчитанным временем и сравнивать каждую очередную точку в складываемых сутках с этим временем. Имеются в виду вопросы округления когда в очередной точке следующих суток время не будет совпадать с идеальным временем на долю точки.
2) Второй подход практический. Создаем что-то типа матрицы. В первой строке этой матрицы посчитаны звездные времена всех точек при данной постоянной времени. Считаем реальное значение звездного времени в первой точке первого часа и в последней точке первого часа. Вставляем тупо все точки в соответствие с посчитанным временем первой и последней точки часового файла во вторую строку этой матрицы. Затем очередной счет первой и последней точки второго часа и так далее. В каком-то часе произойдет переход через сутки. Грубо говоря мы посчитаем значение звездного времени первой точки как например 23h20m10.3c, а значение последней точки как 0h39m49s.7. Для этого переходного файла нужно часть данных записать в конец звездных суток, а другую часть в начало следующих звездных суток. И так далее, пока не сложим все данные за все даты. Подход быстрый по счету, но требует более четкого контроля при переходах через звездные сутки.

**Comment by vtyulb** [comment]
done
