### ISSUE TITLE
новый поиск (Фурье)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#73]
Предлагаю протестировать Фурье
1) Предварительная работа с исходными данными по чистке от помех и вычитании нулевого уровня та же самая.
2) Берется кусок с фиксированной координатой по звездному времени длиной 2048 точек (для коротких данных).
3) Быстрое Фурье от этих данных
3а) Фурье берется от каждой из 6 частот независимо
3б) Возвести в квадрат действительную и мнимую часть, сложить, извлечь квадратный корень с каждой получившейся точки. Длина получившегося массива в 2 раза короче исходных данных.
3в) Складываются все спектры мощности, полученные по 6 частотным каналам для данного интервала времени.
4) Вычитание нулевого уровня  в спектре (если требуется).
4a) Тест правильности работы программы по известным сильным пульсарам. Должны полезть сильные гармоники.
5) Запоминаем звездное время середины интервала на котором брали Фурье для каталога. Запоминаем значения точек получившегося спектра (для вывода на экран и дальнейшего усреднения). Нужно уметь выводить их на экран по той же схеме, что и для обычного поиска. Исходный массив, который раньше выводился на экран справа от среднего двойного профиля не нужен.
5) Смещение примерно на половину обработанного массива
6) Новое быстрое Фурье
7) И так далее по всем лучам и модулям.
8) Обрабатываем новый день и берем интервалы времени для быстрого Фурье максимально близкие по звездному времени к массивам предыдущего дня. Складываем спектры мощности. Для более четкого вылавливания по ночным и дневным данным производим складывание спектров мощности в течении одного месяца. Предусмотреть сложение месячных данных обработчиком. Т.е. захочет сложит все месяцы за все годы. Захочет сложит определенный месяц за все годы и получит оптимальное SNR лишь по ночным данным в пределах какого-то звездного времени.
9) Нужно обсудить, что запоминать в массивах для bsa_analytics

**Comment by vtyulb** [comment]
done
