### ISSUE TITLE
Работа со спектрами мощности

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#74]
А) Принятие решения о дальнейшем анализе.
1) Определение высоты полученной гармоники в сигмах. Взять подряд идущие интервалы в спектре по 16 (возможно это значение изменится кратно двойке) точек. Внутри каждых 16 точек найти максимальное и минимальное значение. Найти разницу между этими значениями разделить ее на 6. Пройтись по всему спектру. Получиться 64 интервала. Выбрать медианное значение сигма по всем интервалам. Сравнивать с этой сигма высоту всех точек в записи после вычитания из этой высоты 3 сигма. Если эта разница больше 5 сигма оставлять этот файл для возможного анализа.
2) Для косвенной проверки пульсар ли мы наблюдаем или ложный объект может быть несколько возможных методов. 
2а) Усредняем спектры за неделю, месяц или за несколько месяцев. Если объект регулярно появляется с этим же периодом в разные недели и месяцы, то он вероятно пульсар. То есть нужна возможность достаточно свободного усреднения спектров по датам (как организовать не знаю).
2б) Если объект с данным периодом появляется в других модулях, далеко отстоящих лучах или на других звездных временах, то он вероятно ложный объект. Нужно каким-то образом предусмотреть возможность такой проверки.
2в) ПРОВЕРЯТЬ. У многих пульсаров будет наблюдаться по несколько гармоник. Так как точность определения частоты у нас равна одной точке, а она в свою очередь определяется постоянной времени и длиной записи, то в самом лучшем случае мы ошибаемся на единицу в третьем знаке после запятой, можем ошибаться и больше. Поэтому нужно проэкспериментировать в определении периода по нескольким гармоникам. Скажем по первой гармонике период получился 1 секунда, по 2ой 2.005 секунды, по 3ей 3.999 секунд. Тогда средний период (1 + 2.005/2 + 3.999/4)=1.00075 Нужно по известным пульсарам проверить есть ли реальное уточнение периода.
4) Всякого рода редкие пульсары могут проявляться один раз за многие дни или месяцы. При обычном усреднении спектров такие объекты просто пропадут. Поэтому должна остаться возможность анализа одиночных спектров. Наиболее очевидный анализ: Найди совпадающие периоды или кратные им числа на заданном SNR на заданном модуле и луче и на заданном промежутке звездного времени за все обработанные даты наблюдений. Это некий аналог того, как искались пульсары раньше по одиночным обработанным записям.
5) Нужно протестировать месяц наблюдений по длинным данным. Длина массива для взятия спектра практически та же, что и для коротких данных (16384 точки). Нарезку из длинных данных хранить невозможно. Но есть возможность сохранить все спектры, полученные по длинным данным, а с исходниками длинных данных работать независимо.
6) После предварительного анализа коротких и длинных данных у меня появляется информация о периоде с точностью не хуже единицы в третьем знаке для коротких и единицы в четвертом знаке для длинных данных. В части PreciseSearch нужно провести дополнительную работу для уточнения. Для коротких данных у нас есть нарезки исходных данных длинной 2048 точек. Для длинных данных такой информации нет. Какой способ работы с длинными данными выбрать я не знаю. Те варианты, что я вижу: а) набиваем таблицу по заданному формату для всех подозрительных объектов. В этой таблице для каждого исследуемого источника у нас звездное время середины интервала, где мы ищем пульсар, период пульсара. Программа последовательно открывает час за часом, месяц за месяцем разные вставляемые диски и для каждого объекта из таблицы проделывает все необходимые дополнительные процедуры по проверке того пульсар мы видим или не пульсар. б) читаем таблицу кандидатов и делаем нарезки длинных данных такие же, как для коротких данных. Эти нарезки сохраняем на диске, а потом работаем с ними перебирая разные варианты поиска в исходных данных. в) возможно тебе придет в голову лучший вариант.
7) Точность определения частоты, а затем и периода по длинным данным в 8 раз (100мсек/12.5мсек) раз выше, чем для коротких данных. Поэтому если есть малейшая возможность таблицы для длинных данных более важны, чем таблицы для коротких данных.
8) Поведение гармоник пульсара не предсказуемо. Если у нас нормальный пульсар, то его первая гармоника всегда будет иметь максимальное SNR. Но очень часто вторая гармоника выше первой. Поэтому в поиске эти две гармоники самые важные.
9) Нужно иметь в виду, что в одной диаграмме может оказаться 2 и более пульсаров. Поэтому проверять нужно все пики высота которых удовлетворяет условию 5сигма.
10) Что проверяем по исходным данным?
Нам нужно найти грубое значение меры дисперсии и положение фазы импульса внутри периода. Тогда можно получить средний профиль пульсара и максимальное соотношение сигнал к шуму. 
10а) Если пульсар виден за конкретный день, то работа с ним тривиальна. Складываем с нужным периодом и проверяем при каких мерах дисперсии в данных получается максимальные высоты пиков на двойном периоде. Для коротких данных перебираем меры дисперсии с шагом 10 от ноля до 200. Для длинных данных перебираем меры дисперсии от 0 до 200 с шагом 1. Строим кривые SNR от меры дисперсии. Шаг по периоду фиксировать и сначала не перебирать как для длинных, так и для коротких данных при первом цикле. Если удается подобрать меру дисперсии, то фиксируем эту меру дисперсии. С учетом этой меры дисперсии складываем длинные данные (короткие игнорируем) и перебираем с шагом плюс минус единица в последнем значащем полученном знаке деленное на 5. Т.е. перебираем всего 10 разных периодов, где первоначально подобранный период посередине между перебираемыми. После уточнения периода можно сложить данные с двойным периодом в каждом частотном канале и вновь попробовать переуточнить меру дисперсии. На выходе этой работы должны быть средний профиль по двойному периоду, рисунок динамического спектра с периодом и кривая SNR для разных мер дисперсии. Для каждого дня когда виден средний профиль нужно выдавать в виде таблицы информацию о дате и UTC времени первого и второго пика в среднем профиле.
10б) Если пульсар слабый и не виден в единичной записи, то здесь есть развилка возможных решений: а) у нас есть нарезка коротких данных за все годы наблюдений. У нас есть ожидаемый период с точностью до третьего или четвертого знака. В коротких данных если точность периода действительно третий знак после запятой, то для секундного пульсара расплывание двойного периода составляет 0.1 секунды на всем интервале. Это не страшно!!! Т.е. берем короткие данные в каждом частотном канале складываем с двойным периодом. То же самое делаем за другие даты и затем пробуем найти наилучший сигнал к шуму с разными задержками между данными за разные дни. Контроль правильности найденных задержек заключается в том, что пики двойного периода должны быть близки по высоте. С теми же задержками по фазе за конкретные дни складываем и другие частотные каналы. Получится 6 частотных каналов. В каждом из них пульсар сложен с двойным периодом. На рисунке SNR от меры дисперсии должны появиться черные полоски, соответствующие мере дисперсии. Определяем эту меру дисперсии с какой-то ошибкой. На выходе выдаем грубое значение меры дисперсии и UTC время импульсов за все дни;
б) верхний вариант автоматической работы если его удастся реализовать. Если он не заработает, то я должен иметь возможность выбрать даты, когда как мне кажется наилучшее отношение сигнала к шуму (можно например эти данные запихивать в директорию и читать эту директорию). Затем делать то же самое, что и в варианте а).

**Comment by vtyulb** [comment]
Я сейчас перечитал текст, и вроде бы при поиске пульсаров у меня реализованы все идеи, которые здесь перечислены. Причем на удивление точно сделаны.
