### ISSUE TITLE
накопление для вспыхивающих, мерцающих и прочих редко появляющихся пульсаров

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#77]
Если пульсар редкий, то он может появиться один раз за много дней. В результате при усреднении по всем дням, мы его можем терять. Для выделения таких пульсаров нужно работать лишь с хорошими днями, когда он был реально виден. Если в панели с фильтрами, до загрузки блоков стоит галочка напротив нового фильтра - "поиск редкостей", то усреднение спектров мощности за весь срок и вывод записей за отдельные дни должен быть ограничен и лишь для тех спектров, которые удовлетворяют набору условий.
а) Period range в каком-то интервале значений. Дело в том, что есть разного рода "левые" гармоники, например 1 секунда или 0.24 секунды. Если выбрать отбор по всем возможным периодам, то спектры с такими периодами будут все время отбираться и вместо редких пульсаров мы будем искать что попало. Следовательно, если я сделаю выбор искать редкие пульсары в интервале периодов 0.25 секунды и до 0.99 секунды, то я буду игнорировать известные сильные "левые" гармоники. После поиска по таким периодам, я могу затем выбрать интервал, например от 1.01 секунд и до 6 секунд (и проигнорирую страшные все забивающие пики вначале), и могу выбрать любой другой интервал какой захочу, лишь бы попасть мимо "левых" гармоник.
б) выбрать значение отбора SNR. 

Например я выбрал значение SNR=5 и периоды от 0.9 до 0.3. Тогда программа после нажатия  "apply", проверяя спектр за очередной считанный день смотрит есть ли в этом спектре пики, имеющие значение SNR=5 и больше в интервале периодов от 0.9 до 0.3 и производит сложение лишь тех спектров, где эти условия выполняются. Это позволит обеспечить накопление периода.

Запуск "поиск редкостей" может быть произведен если есть интервал значений периодов, где мы ищем редкие объекты и указано значение SNR, которое отбирается для дальнейшего усреднения. Если эти две строки не заполнены, то выдавать сообщение "Введите SNR", "Введите "Period range".

**Comment by vtyulb** [comment]
done
