### ISSUE TITLE
дополнительная очистка от плохих данных

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#78]
За месячный интервал находится несколько дней, когда внешний вид спектра говорит о том, что его нельзя складывать с другими спектрами. Шумы в этих спектрах в несколько раз больше, чем шумы в большей части других спектров. Следовательно сложение всех спектров подряд приведет к тому, что сложаться "хорошие" и "плохие" спектры и результат значения сигнала к шуму может быть значительно ухудшен, чем если бы мы отбросили "плохие" спектры и сложили лишь "хорошие". В то же время, если у нас будет 3 года усреднений, то индивидуальные спектры просмотреть практически невозможно и в ручном режиме этого сделать нельзя.
      
Из разговоров с Логвиненко следует, что усиление в приемниках не менялось годами и что оно стабильно в пределах 10-20%. Если это так (что я и проверю, когда ты сделаешь фильтр), то можно отбросить все "плохие" спектры сравнивая медианные значения сигмы шумов за все усредненные дни по данному блоку. Т.е. двойной контроль сигмы шумов. Сначала выбирается медианное значение сигмы шумов внутри блока за день, затем по этим вычисленным сигмам выбирается медианное значение сигмы шумов за все дни. Это значение является базовым для работы с фильтром и с этим значением сравниваются значения всех медианных сигм шумов за конкретные дни.

Предлагаю в блок фильтров ввести галочку с названием "вычищение плохих спектров" (или сам придумай название). Рядом с этой галочкой должно стоять значение, которое является критерием очистки. Например если стоит значение 2.0, то это значит, что после подсчета всех фурье и вычисления в каждом спектре медианного значения сигмы шумов, убери все те спектры из дальнейшего анализа у которых медианное значение сигмы шумов больше 2 (в сравнении с тем, что определено в предыдущем абзаце), а оставшиеся сложи и проводи дальнейший анализ. Значение 1.0 в этом фильтре должно стоять по умолчанию и означать, что никакого анализа сигмы шумов день ото дня делать не нужно.

**Comment by vtyulb** [comment]
done, фильтр "only good-looking spectres", порог 1.3 от медианы. Для применения нужно сделать load data
