### ISSUE TITLE
Новая организация данных

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#80]
Любая фильтрация данных по любому признаку уменьшает общее количество данных. Если в этой фильтрации были недочеты, то используя исходные данные можно фильтрацию провести вновь. Если же мы работаем уже с фильтрованными данными, то восстановить первоисточник может оказаться либо очень долго, либо очень сложно. Проще с самого начала иметь наиболее полные данные. Данные по нарезкам работают быстро. Но как я просмотрел из 1400 исходных дней в этих нарезках иногда сохраняется порядка 800 дней и я не уверен, что было сделано оптимальное удаление 600 дней. 
Предлагаю:
1) Делать нарезку данных после вычитания прямой лишь по уровню 4сигма. Этот уровень определять несколько раз на часовом интервале. Оптимально на 10 или 15 минутах (3-5 нарезанных порций).
2) Дальнейшую фильтрацию переопределять заново. Например если поставить тот фильтр помех, что ты использовал, то окажется данных столько сколько их сейчас. Я в свою очередь предлагал совершенно другой фильтр. Если подходить к этому вопросу строго, то самый правильный фильтр должен быть основан не на ширине дорожки в единицах АЦП, а в единицах реальных потоков (т.к. чувствительность антенны может меняться по зимним и летним данным или из-за мерцаний или из-за изменения усиления в тракте антенны). Если у нас будут собраны все исходные нарезки, то не использовать их, потому что они не прошли фильтр существенно легче, чем вновь нарезать все данные для использования нового фильтра чистки помех.

**Comment by vtyulb** [comment]
Как ни странно, все перечисленные задачи сделаны
