### ISSUE TITLE
правильное определение высоты гармоники в сигмах.

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#81]
Как я уже писал сигму можно определять на кусочках длиной16 точек. Затем определяется медианное значение на всей длине нарезки. По ходу массива определяем высоты всех точек. Рядом (за две-три точки от проверяемой. Сделано это для того, что если нарвались на реальную гармонику не определить среднее с учетом этой гармоники.) смотрим среднее по 16 точкам (среднее рядом). Напоминаю, что сигма текущее по 16 точкам равна максимальное значение в этих точках - минимальное значение в этих точках делить на 6 (нужно потестировать. Возможно окажется не 6, а 5 или 4). Затем из 64 полученных сигма выбираем медианное значение.
 
Далее по формуле: H_в_сигмах = (значение проверяемой точки - среднее рядом)/sigma_mediana

В таблицу вносим не только самую большую гармонику в сигмах, но и другие пики по заранее заданному уровню

**Comment by vtyulb** [comment]
Сделано, но по-другому
