### ISSUE TITLE
сглаживание спектров (для длинных данных. Пока не трогать)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#82]
На длинных данных очень часто будет случаться, что длительность импульса несколько точек. Это означает, что и в спектре длительность спектра тоже будет несколько точек. Но тогда SNR будет не оптимальным и слабые пульсары будут пропускаться. Нужно будет в фильтрах поставить "Сглаживание спектра". В окошке должно стоять целое количество точек сглаживания. Если например стоит число 3, то по спектрам нужно пройтись скользящим средним с шагом 3. Возможно, что эти фильтры могут понадобиться и по коротким данным, но это маловероятно (с другой стороны один из найденных нами пульсаров имеет длительность импульса 0.25-0.3 и для него такой фильтр улучшил бы SNR). 
Не забыть если использован такой фильтр, то и сигма нужно вновь определять по 16 точкам. Старыми сигма пользоваться нельзя.

**Comment by vtyulb** [comment]
Закрыто из-за #103
