### ISSUE TITLE
оценка периода (пока не трогать, буду проверять нужность!)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#83]
Предлагаю период определять с использованием всех гармоник. Предположим, что мы наблюдаем на заданном SNR (должно быть не меньше 7, а может и 10) несколько гармоник пульсара. Предположим, что на заданном SNR - это гармоники 1,3,5,6. Тогда период определяем как:
Период=(период1 + 3_период3 + 5_период5 + 6\* период6)/делить на 4.

**Comment by vtyulb** [comment]
Закрыто из-за #103
