### ISSUE TITLE
новая перенарезка и предварительная чистка помех

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#85]
1) Подобрать какое-то адекватное вычитание нулевого уровня!!!
2) В программе используется сигма шумов на часовом интервале. На самом деле в течение часа шумы могут сильно расти и падать, поэтому интервал оценки шумов для работы с нарезкой данных нужно сократить до размера одной нарезки в 2048 точек. Внутри этой нарезки для каждого частотного канала берем зоны по 128 точек, в каждой зоне (всего их 20) находим сигма шумов. Выбираем медианное сигма. Убираем любые выбросы, которые больше чем медианное значение в 4 или 5 раз. Никакой другой чистки делать не надо!!! Вообще говоря если была очень плохая помеховая обстановка, то полностью шумы таким алгоритмом убрать нельзя, но мы избавимся от плохих данных на следующих этапах.
3) Получаем файл у которого за каждый из обработанных дней, за каждые 2048 точек и в каждом частотном канале есть предварительно очищенные данные (либо храним все это в оперативке!).
4) Делаем новые оценки сигма шумов по полному интервалу одной нарезки в 2048 точек для каждого частотного канала за каждый день. Если у нас остались недоочищенные данные, то сигма шумов будет большой в этой нарезке, по сравнению с нарезками этого же звездного времени но за другие дни. ВАЖНО!!! Нарезки храним все и с плохими и с хорошими данными, а способ выкидывания плохих подбираем в ходе дальнейшей работы. 
5) Задаем критерий по которому выкидываем плохие нарезки. Предварительно проходимся по выбранному звездному времени (блоку) и ищем медианное значение сигмы шумов за все обрабатываемое время. Например, мы задаем критерий двойка. Тогда из нарезок за одно и то же звездное время, но за разные дни спектр мощности не считаем и не суммируем, если сигма шумов, определенная на 2048 точках больше двойной сигмы медианной, определенной по всем нарезкам блока. Сейчас нельзя определить этот критерий точно. На мой вкус он должен быть между 1.5 и 3 (нужно подбирать и поэтому это лучше сделать параметром). Таким образом на пятом шаге мы оставляем для дальнейшего анализа лишь те нарезки, у которых шумы более менее близкие (отличающиеся друг от друга от 1.5 до 3 раз). Этот способ позволит избавится от мест с большими помехами, длительность которых составляет десятки секунд или минуты и которые могут остаться в данных после шага 2. 
6) Перед взятием фурье и получением спектра мощности в каждой нарезке, делим все точки на значение сигмы шумов, определенную для данной нарезки. Т.е. после такого деления сигма шумов в нарезке, отобранной для фурье и дальнейшего усреднения, будет равна единице. Мы таким образом сделаем все нарезки одинаковыми по шумам. Они и складываться будут более менее правильно. 
7) Перенарезку сделать на 4 месячном интервале! Этого вполне достаточно для анализа адекватности работы

**Comment by vtyulb** [comment]
Сделан фильтр "good-looking spectres", убирает спектры с шумами выше 1.3 медианного
