### ISSUE TITLE
нарезка нижних лучей БСА3 короткие данные

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#86]
1) модули 1,2,3,4 обрабатываются так же, как и верхние лучи БСА3 (т.е. предварительная чистка от помех и нарезка по кускам в 2048 точек). Не забыть вставить в программу расположение лучей из таблицы со склонениями по аналогии с верхней площадкой.
2) модули 5 и 6 обрабатываются по следующей схеме:
         а) модуль 5 луч 1 используются частотные каналы 1,2,3,4 и берутся частотные каналы
                                                                                                      5,6 из модуль 5 луч2
         б) модуль 5 луч 2 используются частотные каналы 1,2,3,4 и берутся частотные каналы
                                                                                                     5,6 из модуль 5 луч3
                                        ###  **и до**
         в) модуль 6 луч 7 используются частотные каналы 1,2,3,4 и берутся частотные каналы
                                                                                                     5,6 из модуль 6 луч 8
        г) модуль 6 луч 8 используются лишь 4 частотных канала под номерами 1,2,3 и 4

**Comment by vtyulb** [comment]
done
