### ISSUE TITLE
нарезка нижних лучей БСА3 длинные данные

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#87]
1) модули 1,2,3,4 обрабатываются так же, как и верхние лучи БСА3. Т.е. делаем согласованную нами обработку (сохранение лишь спектров мощности) 32 частотных каналов. 
2) модули 5 и 6 обрабатываются по следующей схеме:
а) модуль 5 луч 1 используются частотные каналы 1,2,3,...22,23 и берутся частотные каналы
24,25,...31,32 из модуль 5 луч2
б) модуль 5 луч 2 используются частотные каналы 1,2,3,,...22,23 и берутся частотные каналы
24,25,...31,32 из модуль 5 луч3
### и до
в) модуль 6 луч 7 используются частотные каналы 1,2,3,,,...22,23 и берутся частотные каналы
24,25,...31,32 из модуль 6 луч 8
г) модуль 6 луч 8 используются лишь 23 частотных канала под номерами 1,2,3,,...22,23

**Comment by vtyulb** [comment]
done
