### ISSUE TITLE
дополнительный фильтр для выбора хороших данных

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#88]
Рядом с фильтрами убирания плохих спектров и анализа внутри выбранных периодов добавить еще один фильтр отбора лучших данных.
Суть фильтра: учитывая все ранее зажатые фильтры из оставшегося выбрать заданный процент данных у которых в исходных нарезках минимальный определенный шум. 
Например: У нас 1000 дней нарезки в данном блоке. После зажатия "убрать плохие спектры" осталось 500. Если я в новом фильтре поставлю 50%, то это означает, что по исходным нарезкам, соответствующим  500 спектров, выбери 50% нарезок (т.е. 250 дней) с минимальными сигма шумов в исходных данных, определенных по той схеме, что ты используешь (т.е. сигма определенное после выкидывания 30% максимальных точек и 30% минимальных точек)

**Comment by vtyulb** [comment]
Закрыто из-за #103
