### ISSUE TITLE
Проверка истинности пульсара

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#90]
В ходе нашей работы находятся кандидаты в пульсары. Характеристики "правильных" пульсаров:
1) повторяемость по звездному времени. 
2) не нулевая мера дисперсии
3) тайминг  (**EDIT** пока только для сильных пульсаров)
4) при усреднении с двойным периодом и при известной мере дисперсии должны появляться два пика, расстояние между которыми в точках, приблизительно равно расстоянию до максимума первого пика + расстояние после максимума второго пика. Относительная разница высот импульсов при двойном периоде не может превышать 50%.

1) сделано
2) сделано для пульсаров, видимых в одиночных записях в "precise search".
3) Схема работы для пульсаров, видимых в одиночной записи (делается для двойных периодов): запоминание координат UTС времени максимумов импульсов при поиске с двойным периодом и вывод этих координат в выходной файл в формате: дата UTC, время UTC первого максимума, затем новая строка в которой дата UTC, время UTC второго максимума, затем следующая дата и следующие UTC времена максимумов импульсов. Если в presice search задано точное значение периода (с нужной точностью) и меры дисперсии для поиска UTС, то, следовательно, не нужно перебирать периоды и меры дисперсии (я их найду предварительно по самым лучшим отобранным записям в той же программе presice search), а нужно сложить с заданным периодом импульсы, запомнив UTС время первой складываемой точки. Относительно этой точки и высчитывать UTC координаты вершин. Тест программы нужно сделать по самым сильным пульсарам, видимым в исходных записях. Имя выходного файла с данными по временам UTC пиков должно содержать J_name пульсара. Файлы, по которых ищутся вершины, берутся по отобранным лучшим нарезкам для данного пульсара.
Схема работы для пульсаров не видимых в одиночных записях (**пока отложить**):
Слабые пульсары не будут видны в исходных записях после усреднения по периоду и с известной мерой дисперсии. Например, мы обнаружили пульсар в предварительном поиске и определили его период. Полагаем при этом, что точность определения периода такова, что при сложении всех импульсов на трех минутах координата вершины расплывается не больше, чем на точку. Предположим, что период пульсара 1 секунда. Время накопления 3 минуты. Тогда всего будет 180 импульсов. Если мы знаем период с точностью 0.001 секунды, то на 180 импульсах получим уход вершины импульса пульсара в последнем складываемом периоде относительно положения  вершины импульса в первом складываемом периоде на 0.001_180=0.18 секунды. То есть максимальное расплывание секундного пульсара будет на 2 точки, если говорить о коротких данных и на примерно 20 точек если говорить о длинных данных. Т.е. желательная точность 0.0005 для коротких данных при периоде в 1 секунда, а т.к. минимально возможные периоды, определяемые из спектра мощности 0.2 секунды, то желательная точность 0.0001 секунды. Ситуация с длинными данными сложнее и будем ее решать позже. Самые короткопериодические пульсары будут иметь периоды 25 мсек по длинным данным. В спектре мощности будет в 8 раз больше точек, значит и точность определения периода повыситься в 8 раз. Сейчас наша точность  болтается в единицах третьего знака после запятой, а будет болтаться в единицах четвертого знака после запятой по длинным данным. При этом при точности периода 0.0001секунды и периоде кандидата в пульсары в 25 мсек получим на интервале 3 минуты 7200 импульсов и уход положения вершины в последнем импульсе относительно положения вершины в первом импульсе на 0.0001_7200=0.72 секунды (ошибка на 30 периодов). Т.е. необходимая точность определения периода по длинным данным для тайминга нужна в сто раз лучше и должна быть равна 0.000002секунды, тогда 0.000002_7200=0.0144секунды=14.4 мсек, что соответствует расплыванию среднего профиля на одну точку (постоянная времени 12.5 мсек).
Таким образом для пульсаров, невидимых в одиночных записях, но обнаруженных нами в ходе работ по усреднению спектров за долгий срок нужно:
а) фиксировать даты всех дней, по которым пульсар был предварительно найден;
б) по этим датам в первичных данных, либо по нарезкам с данными (если известно UTC время первой точки и UTC дата нарезки) проводить многопараметрический анализ поиска максимумов импульсов, точного периода и меры дисперсии пульсара.
в) задача б) заключается в поиске максимума при переборе периодов относительно заданного с шагом 0.0001, перебором мер дисперсии с шагом 10 от 0 до 200 и поиском кросскорелляции по всем(?) (__обсуждать!!!_*) файлам со всевозможными шагами и мерами дисперсии. Все кросскорелляции делать относительно первого обрабатываемого массива, смещение массивов для кросскорелляции делать всегда в одну сторону. Цель программы: запомнить точные сдвиги в точках для каждого массива кросскорелляции. Для длинных данных перебор периодов с шагом 0.000002 секунды, перебор мер дисперсии с шагом 2 от 0 до 200 и кросскорелляция массивов.
Тест схемы по сильным известным пульсарам!!!
4) Нужно сделать. В самом пункте сверху отражено, то что должно быть сделано.

**Comment by vtyulb** [comment]
1,2,4,5,6 - функционал есть
3 - тайминг стоит отдельной задачей #132 
7,8 - UTC метки первого импульса выдаются по контекстному меню в pulsar analytics, все остальное вроде бы тоже есть
