### ISSUE TITLE
нарезка длинных данных (общие соображения)

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#91]
1) Очевидно, что хранить исходную нарезку из длинных данных нет возможости
2) Очевидно, что хранить спектры от длинных данных есть возможность, так как спектр по объему отличается от исходных данных в 66 раз (33 канал отбрасывается, спектры мощности 32 каналов усредняются + спектр в два раза короче чем было бы точек в нарезке). Следовательно, если у нас сейчас примерно 1.5 года длинных данных по 2.5 терабайта за год, то объем посчитанных спектров по длинным данным будет 2.5*18/66 примерно равно 700 мегабайт.
3) вопрос заключается в том, можем ли мы для наших анализов при поиске пульсаров использовать лишь спектры от длинных данных.
а) предварительное выбрасывание самых плохих данных делается в ходе предварительного анализа;
б) фильтры работающие с уже готовыми фурье спектрами будут также работать после загрузки всех спектров данного блока;
в) фильтры работающие с исходными нарезками работать не будут, так как они основаны на переоценках сигмы шумов. Вопрос: Можно ли после предварительного отбрасывания откровенно плохих данных оставить тот необходимый минимум информации от нарезок, который будет достаточен для работы оставшихся фильтров???. Навскидку нужна сохраненная информация по номеру нарезки (блока), имени файла (т.е. даты наблюдений), сигмы шумов в отдельных каналах по схеме выброса 30% самых больших и самых маленьких значениях в массиве нарезки). Используем ли мы еще хоть что-то из исходных нарезок???
г) вопрос об уточнении периода, меры дисперсии будет все равно решаться в presice search или более замысловатым образом для пульсаров, которые не видны в одиночных записях.

**Comment by vtyulb** [comment]
Давно сделано
