### ISSUE TITLE
Плотность потока в единицах АЦП + определение времени начала импульса

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#95]
Две задачи могут выполняться одновременно как по коротким, так и по длинным данным.
1) Читаем файл в котором размещены данные по известным или найденным нами пульсарам. 
имя_пульсара; координаты(по альфа и дельта); модуль; луч; период; мера_дисперсии;
2) Выбираем диск с данными (если короткие данные, то они могут быть все на одном диске, если длинные данные, то нужно предусмотреть возможность менять диски после обработки)
3) Используя пункт (1) выбираем из таблицы пульсар и обрабатываем его. Обработка для последующего тайминга заключается в следующем: запоминаем номер точки (время по UTC) с которой начинается сложение импульсов, складываем с двойным импульсом, получаем обычный двойной профиль у которого мы знаем UTC координату первой точки, ищем на какие точки приходится первый и второй импульс в среднем профиле, выводим в таблицу UTC время первого и второго максимума, а также UTC дату, работу проделываем за все дни, месяцы и годы. Результаты обработки игнорируются, если сигнал шум в получившемся среднем профиле меньше 5.
4) Обработка для плотности потока полный аналог. В полученном среднем профиле смотрится высота импульсов в единицах АЦП и оценивается среднее по двум импульсам. Этот метод должен работать хорошо в том случае, когда эффективная площадь антенны и усиление не меняется день ото дня. Мои оценки показывают, что типичные изменения составляют 20-30%. Т.е., переменность в полученных данных будет значимой (т.е. будет истинная переменность связанная с самим пульсаром или с мерцаниями на межзвездной среде), если будет регистрироваться на уровне 50% и больше, что не очень хорошо, но в целом приемлемо. Если оценивать высоту импульсов в единицах ступеньки, то точность должна улучшиться примерно до 3-5%. Как это делать описано в задаче 59. Напоминаю также, что высота импульса в единицах АЦП должна быть близкой за один и тот же день для длинных и коротких данных (отличие может быть на десятки процентов, может быть в два раза и при этом в длинных данных это значение всегда будет больше, но не может быть отличия в десятки раз (см. задачу 55)).
5) На выходе работы программы образовывать отдельные файлы для разных пульсаров. Имя файла - это название пульсара из таблицы с добавкой на конце имени "timing" или "flux_ADC_rectangle". Внутри таблицы по колонкам располагаются дата UTC (если знаешь как делать Юлианскую дату, то и ее тоже), время UTC первого импульса, время UTC второго импульса. Вторая таблица такая же, но вместо времени первого импульса плотность потока в единицах АЦП, а вместо второго времени плотность потока в единицах ступеньки.

Заодно нужно смотреть задачи 55 и 59 и закрыть их.

**Comment by vtyulb** [comment]
Вроде бы пару недель назад полностью сделал
