### ISSUE TITLE
Допиливание сигнала к шуму для режима "pulsar search ----> pulsar analytics"

### ISSUE THREAD

**Issue by STyulb** [vtyulb/BSA-Analytics#98]
При запуске "pulsar analytics" подсчет сигнала к шуму идет некорректно и из-за этого очень затруднен поиск слабых пульсаров. Переделка относится лишь к длинным данным!!! Делаем следующие процедуры.
1) Берем номер точки первого максимума, который программа нашла в автоматическом режиме. Запоминаем это значение. Ищем номер точки второго максимума прибавляя к точке первого максимума ровно половину длины массива. Смотрим высоту точки второго максимума и высоты всех точек в окрестности плюс минус 2 точки. Самую большую высоту в окрестности второго максимума считаем пиком, связанным с пульсаром. В результате процедур имеем высоту точки первого максимума и высоту точки второго максимума. Называем высотой среднего профиля пульсара их полусуму. По тексту ниже H_profil.
2) Исключаем из массива точек двойного профиля точки максимума двойного профиля и две точки соседние с вершинами. Если пульсар был периодом 1.25 секунды, то в двойном профиле было ровно 200 точек и мы из них откинули 6 точек.
3) На всей длине массива двойного профиля выстраиваем точки по ранжиру. Находим медианное значение у оставшихся точек (H_mediana). Берем максимальное оставшееся значение вычитаем минимальное оставшееся значение точек массива и делим эту разницу на 4. Называем то, что получилось сигма_шумов. Для тех значений, где у нас раньше было SNR=0, присваиваем SNR=1.
4) Теперь для графика SNR/DM значение SNR определяем следующим образом: 
                                  SNR=H_profil/сигма_шумов
Для тех значений, где у нас раньше было SNR=0, присваиваем SNR=1.

**Comment by vtyulb** [comment]
Закрыто из-за задачи 100
